---
config:
  layout: elk
---
erDiagram
    edna_sample {
        varchar sample_label PK
        varchar edna_process
        varchar illumina_name
        varchar station_name
        varchar season
        double line_src
        double station_src
        double line
        double station
        varchar site_key
        double depth_m
        double latitude
        double longitude
        varchar cruise_label
        date nominal_date
        varchar site_ym
        varchar cast_sample_key
        varchar bottle_sample_key
        varchar cruise_key
        timestamp datetime_start_utc
        geometry geom
        varchar grid_key
    }
    edna_detection {
        varchar sample_label FK
        varchar species_code
        int detected
    }
    dataset {
        varchar provider
        varchar dataset
        varchar dataset_name
        varchar dataset_name_short
        varchar category
        varchar color
        varchar description
        varchar citation_main
        varchar citation_others
        varchar link_calcofi_org
        varchar link_data_source
        varchar link_others
        varchar tables
        varchar coverage_temporal
        varchar coverage_spatial
        varchar license
        varchar pi_names
        varchar doi
        varchar license_url
        varchar acknowledgement
        varchar contact
    }
    edna_sample ||--o{ edna_detection : "sample_label"
    classDef lightblue stroke:#ADD8E6,stroke-width:3px
    class edna_sample,edna_detection lightblue
    classDef white stroke:#FFFFFF,stroke-width:3px
    class dataset white
