---
title: "explore_station-vector"
author: "Ben Best"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Setup gcloud and ssh tunneled to database per 
https://github.com/CalCOFI/server#ssh-tunnel-connection-to-postgis-db.

```{r}
librarian::shelf(
  calcofi/calcofi4r, 
  here, leaflet, sf)
source(here("../apps/libs/db.R"))

table(calcofi4r::stations$is_cce)     # 113
table(calcofi4r::stations$is_ccelter) # 66
table(calcofi4r::stations$is_sccoos)  # 9

sta_n <- tbl(con, "ctd_casts") %>% 
  group_by(sta_id) %>% 
  summarize(
    n = n(),
    date_min = min(date, na.rm=T),
    date_max = max(date, na.rm=T)) %>% 
  arrange(desc(n)) %>% 
  collect() %>% 
  left_join(
    calcofi4r::stations,
    by = "sta_id")

sta_n

n_min_cce <- sta_n %>% 
  filter(is_cce) %>% 
  pull(n) %>% 
  min() # 1

n_min_ccelter <- sta_n %>% 
  filter(is_ccelter) %>% 
  pull(n) %>% 
  min() # 124

sta_nmin <- sta_n %>% 
  filter(n >= n_min_ccelter) %>% 
  mutate(
    cat = case_when(
      is_cce  & is_ccelter  ~ "ccelter",
      is_cce  & !is_ccelter ~ "cce",
      !is_cce & !is_ccelter ~ "neither",
      TRUE ~ "other")) %>% 
  st_as_sf()
table(sta_nmin$cat)

leaflet() %>% 
  addProviderTiles(providers$Stamen.Toner) %>% 
  addCircleMarkers(
    data = sta_nmin %>% 
      filter(cat == "ccelter"))

 mapview(sta_nmin, zcol = "n")
  View()

sta_n %>% 
  filter(is_sccoos & !is_ccelter)

```

