---
title: "explore_duckdb"
editor: visual
---

## Overview

Goals:

- [ ] Write database tables to duckdb

- [ ] Upload to S3 bucket publicly available online
- [ ] View tables

```{r}
librarian::shelf(
  calcofi/calcofi4db, 
  DBI, dplyr, DT, duckdb, fs, glue, here, tibble, tidyr,
  quiet = T)
options(readr.show_col_types = F)

# set up paths
is_server <-  Sys.info()[["sysname"]] == "Linux"
dir_data  <- ifelse(
  is_server,
  "/share/data",
  "~/My Drive/projects/calcofi/data")
dk_db     <- glue("{dir_data}/swfsc.noaa.gov/calcofi.duckdb")

# get database connection
con_pg <- get_db_con(c("dev"))
con_dk <- dbConnect(duckdb(), dbdir = dk_db, read_only = F)

tbls = dbListTables(con_pg)
#  [1] "cruise"   "egg"      "grid"     "larva"    "net"      "ship"     "site"     "site_seg"
#  [9] "species"  "tow"      "tow_type"
for (tbl in tbls){
  if (!(dbExistsTable(con_dk, tbl)))
    dbReadTable(con_pg, tbl) %>% 
      dbWriteTable(con_dk, tbl, .)
}
```


## Close Connection

```{r cleanup}
dbDisconnect(con_dk, shutdown = T); duckdb_shutdown(duckdb()); rm(con_dk)
```


