---
title: "Depth Profile Plot Explore"
author: "Ben Best"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

## Packages & setup

```{r}
# packages
if (!require("librarian")){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  calcofi/calcofi4r, 
  # marmap,
  cmocean, dplyr, DT, glue, here, interp,
  mapview, plotly, proj4, purrr, sf, skimr, tidyr)
mapviewOptions(fgb = F)

source(here("../apps/libs/db.R"))
```

```{r}
calcofi4r::stations %>% 
  st_drop_geometry() %>% 
  skimr::skim()
nrow(calcofi4r::stations) # 2,634

mapview(calcofi4r::stations, zcol="sta_id_line")
```

## Weber & Moore (2013)

Source: Appendix of Weber & Moore (2013) [Corrected conversion algorithms for the CalCOFI station grid and their implementation in several computer languages](http://calcofi.org/publications/calcofireports/v54/Vol_54_Weber.pdf). _California Cooperative Oceanic Fisheries Investigations Reports_

```{r}
deg2rad <- function(deg) deg * pi / 180
rad2deg <- function(rad) rad * 180 / pi
inverse_mercator <- function(mercatorlat, iterations = 3){ 
  
  approxlat <- mercatorlat
  
  iterlatitude <- function(mercatorlat, approxlat){
    approxlat <- 2 * (atan(exp(deg2rad(mercatorlat) + 0.00676866 * sin(deg2rad(approxlat)))) * 180 / pi - 45)
    approxlat
  }
  
  for (i in 1:iterations)
    approxlat <  iterlatitude(mercatorlat, approxlat)
  
  approxlat
}

to_mercator <- function(latitude) { 
  y <- rad2deg(log(tan(deg2rad(45 + latitude / 2))) - 0.00676866 * sin(deg2rad(latitude)))
  y
}

station_to_latlon <- function(x, roundlines = true) {
  
  if (length(x) == 2 & class(x) != 'matrix'){
    x <- matrix(x, 1, 2)
  }
  line <- x[, 1]
  station <- x[, 2]
  
  reflatitude <- 34.15 - 0.2 * (line - 80) * cos(deg2rad(30))
  latitude <- reflatitude - (station - 60) * sin(deg2rad(30)) / 15
  l1 <- (to_mercator(latitude) - to_mercator(34.15)) * tan(deg2rad(30))
  l2 <- (to_mercator(reflatitude) - to_mercator(latitude)) / (cos(deg2rad(30)) * sin(deg2rad(30)))
  longitude <- -1 * (l1 + l2 + 121.15)
  cbind(lon = longitude, lat = latitude)
}
# https://proj.org/operations/projections/calcofi.html # -121.15 34.15   80.00   60.00
station_to_latlon(c(80.0, 60.0))
#          lon   lat
# [1,] -121.15 34.15

lonlat_to_station <- function(x){
  # x = c(-121.15, 34.15)
  if (length(x) == 2 & class(x) != 'matrix'){
    x <- matrix(x, 1, 2)
  }
  longitude <- x[, 1]
  latitude  <- x[, 2]
  # longitude <- -121.15 
  # latitude  <- 34.15
  
  # assume we're in the western hemispere
  longitude[longitude > 180] <- -1 * (longitude[longitude > 180] - 360)
  longitude[longitude < 0]   <- longitude[longitude < 0] * -1
  
  l1 <- (to_mercator(latitude) - to_mercator(34.15)) * tan(deg2rad(30))
  l2 <- longitude - l1 - 121.15
  mercreflatitude <- l2 * cos(deg2rad(30)) * sin(deg2rad(30)) + to_mercator(latitude)
  reflatitude     <- inverse_mercator(mercreflatitude)
  
  line    <- 80 - (reflatitude - 34.15) * 5 / cos(deg2rad(30))
  station <- 60 + (reflatitude - latitude) * 15 / sin(deg2rad(30))
  
  cbind(line = line, station = station)
}
# https://proj.org/operations/projections/calcofi.html # 80.0 60.0   -121.15 34.15
lonlat_to_station(c(-121.15, 34.15))
# 68.42567 120.142 # Doh! Wrong answer
```

## `proj-bin`

For Debian Linux, install `proj` binary:

```{bash}
sudo apt-get install proj-bin
which proj
```

## f() with proj-bin

Define functions:

```{r}
lonlat_to_stationid <- function(lon, lat){
  # convert station ID to lon, lat using the proj library
  
  system(glue("echo {lon} {lat} | proj +proj=calcofi +epsg=4326 -f '%05.1f'"), intern=T) %>%
    stringr::str_replace("\t", " ")
}
lonlat_to_stationid(-121.15, 34.15) # "080.0 060.0"

stationid_to_lonlat <- function(stationid){
  # using 5th decimal place, a la CCE_Stations.txt
  
  system(glue("echo {stationid} | proj +proj=calcofi +epsg=4326  -I -d 5"), intern=T) %>%
    stringr::str_replace("\t", " ")
}
stationid_to_lonlat("080.0 060.0") # "-121.15000 34.15000"

# A: offshore/1, line/1
sta_a.1.1 <- calcofi4r::stations %>% 
  st_drop_geometry() %>% 
  mutate(
    x = round(sta_id_station),
    y = round(sta_id_line)) %>% 
  group_by(x, y) %>% 
  summarize(
    n = n(),
    .groups = "drop") %>% 
  mutate(
    z = glue("{y} {x}")) %>%
  mutate(
    lonlat = map_chr(z, stationid_to_lonlat)) %>% 
  separate(lonlat, c("lon", "lat"), sep = " ", convert=T) %>%
  st_as_sf(
    coords = c("lon", "lat"), crs=4326, remove = F) %>% 
  rename(
    n_stations = n,
    sta_id = z)
nrow(sta_a.1.1) # 2,270
mapview(sta_a.1.1, zcol="y")

# B: offshore/5, line/2
sta_b.5.2 <- calcofi4r::stations %>% 
  st_drop_geometry() %>% 
  mutate(
    x = round(sta_id_station/5) * 5,
    y = round(sta_id_line/2) * 2) %>% 
  group_by(x, y) %>% 
  summarize(
    n = n(),
    .groups = "drop") %>% 
  mutate(
    z = glue("{y} {x}")) %>%
  mutate(
    lonlat = map_chr(z, stationid_to_lonlat)) %>% 
  separate(lonlat, c("lon", "lat"), sep = " ", convert=T) %>%
  st_as_sf(
    coords = c("lon", "lat"), crs=4326, remove = F) %>% 
  rename(
    n_stations = n,
    sta_id = z)
nrow(sta_b.5.2) # 1,128
mapview(sta_b.5.2, zcol="y")

# C: offshore/10, line/3
sta_c.10.3 <- calcofi4r::stations %>% 
  st_drop_geometry() %>% 
  mutate(
    x = round(sta_id_station/10) * 10,
    y = round(sta_id_line/3) * 3) %>% 
  group_by(x, y) %>% 
  summarize(
    n = n(),
    .groups = "drop") %>% 
  mutate(
    z = glue("{y} {x}")) %>%
  mutate(
    lonlat = map_chr(z, stationid_to_lonlat)) %>% 
  separate(lonlat, c("lon", "lat"), sep = " ", convert=T) %>%
  st_as_sf(
    coords = c("lon", "lat"), crs=4326, remove = F) %>% 
  rename(
    # sta_offshore = x,
    # sta_alongshore = y,
    n_stations = n,
    sta_id = z)
nrow(sta_c.10.3) # 702
mapview(sta_c.10.3, zcol="y")

# D: offshore/10, line/4
sta_d.10.4 <- calcofi4r::stations %>% 
  st_drop_geometry() %>% 
  mutate(
    x = round(sta_id_station/10) * 10,
    y = round(sta_id_line/4) * 4) %>% 
  group_by(x, y) %>% 
  summarize(
    n = n(),
    .groups = "drop") %>% 
  mutate(
    z = glue("{y} {x}")) %>%
  mutate(
    lonlat = map_chr(z, stationid_to_lonlat)) %>% 
  separate(lonlat, c("lon", "lat"), sep = " ", convert=T) %>%
  st_as_sf(
    coords = c("lon", "lat"), crs=4326, remove = F) %>% 
  rename(
    # sta_offshore = x,
    # sta_alongshore = y,
    n_stations = n,
    sta_id = z)
nrow(sta_d.10.4) # 611
mapview(sta_d.10.4, zcol="y")

hull <- st_convex_hull(st_union(calcofi4r::stations)) %>% 
  st_transform(leaflet:::epsg3857) %>% 
  st_buffer(1000)

sta_d.10.4_v <- sta_d.10.4 %>% 
  st_transform(leaflet:::epsg3857) %>% 
  st_union() %>% 
  st_voronoi(hull)

sta_d.10.4_vp <- sta_d.10.4_v %>% 
  st_collection_extract(
  type = "POLYGON")
sta_d.10.4_vpi <- st_intersection(sta_d.10.4_vp, hull)
sta_d.10.4_vpig <- sta_d.10.4_vpi %>% 
  st_transform(4326)

mapview(sta_d.10.4_vpi) +
  mapview(sta_d.10.4, zcol="y")

librarian::shelf(
  rnaturalearth, rnaturalearthdata)
# devtools::install_github("ropensci/rnaturalearthhires")

land_l <- ne_countries(scale = "large", returnclass = "sf") %>% 
  st_combine() %>% 
  st_make_valid()
# land_m <- ne_countries(scale = "medium", returnclass = "sf")
# land_s <- ne_countries(scale = "small", returnclass = "sf")

# sta_d.10.4_vpigl_0 <- sta_d.10.4_vpigl
sta_d.10.4_vpigl <- st_difference(sta_d.10.4_vpig, land_l)
mapview(sta_d.10.4_vpigl, alpha.regions = 0.5) +
  mapview(sta_d.10.4, zcol="y", cex=2)
```

## NEW: `sf::st_crs("+proj=calcofi")`

```{r}
st_crs("+proj=calcofi")

# 80.00 60.00 -> -121.15 34.15   
pt_cc <- tribble(
  ~alongshore, ~offshore,
  80.00, 60.00) %>% 
  st_as_sf(
    coords = c("alongshore", "offshore"), 
    crs = st_crs("+proj=calcofi"))
pt_cc # 80 60

pt_gcs <- pt_cc %>% 
  st_transform(4326) # -121.15 34.15

pt_gcs %>% 
  st_transform(st_crs("+proj=calcofi")) # 80, 60

# freq of alongshore
y <- stations %>% 
  group_by(sta_id_line) %>% 
  summarize(n = n())

y %>% st_drop_geometry() %>% datatable()
  

y %>% st_drop_geometry() %>% arrange(desc(n)) %>% head()
# 1        90      82
# 2        93.3    65
# 3       100      53
# 4       120      53
# 5        83.3    47
# 6       110      47

dbListFields(con, "ctd_casts")

lns <- tbl(con, "ctd_casts") %>% 
  group_by(stline) %>% 
  summarize(cnt = n()) %>% 
  arrange(desc(cnt)) %>% 
  collect()
View(lns)
lns10 <- head(lns, n=10)

lns10
#  1   90      4222
#  2   93.3    3611
#  3   86.7    2609
#  4   83.3    2387
#  5   80      2233
#  6   76.7    1629
#  7  100      1243
#  8  120      1216
#  9  110      1084
# 10   70      1025
lns10 <- lns10 %>% pull(stline)


seq(90, 93.3, by=0.3)
lnsv <- seq(min(lns10), max(lns10), by=0.3)
sum(lns10 %in% lnsv) # 2

lnsv2 <- c(
  seq(90, max(lns10), by=0.3),
  seq(90, min(lns10), by=-0.3)[-1]) %>% 
  sort()
sum(lns10 %in% lnsv2) # 4

hist(stations$sta_id_line)

sta <- tbl(con, "ctd_casts") %>% 
  group_by(ststa) %>% 
  summarize(cnt = n()) %>% 
  arrange(desc(cnt)) %>% 
  collect() # %>% 
  # head(n=10)

View(sta)

sta_odd <- sta %>% 
  mutate(
    mod5 = ststa %% 5) %>% 
  filter(mod5 != 0)

# ∆ 0.3, 10 (alongshore, offshore); ctr: 90, 60

sta_cc <- stations %>% 
  st_transform(st_crs("+proj=calcofi"))

makegrid()

yx <- st_coordinates(sta_cc)

# alongshore
min(yx[,1])
max(yx[,1])
# offshore
min(yx[,2])
max(yx[,2])


# ∆ 3.3, 10 (alongshore, offshore); ctr: 90, 60
cy <- 90
cx <- 60
dy <- 3.3
dx <- 10
vy <- c(
  seq(cy, max(yx[,1]), by = dy),
  seq(cy, min(yx[,1]), by = -1*dy)[-1]) %>% 
  sort()
vx <- c(
  seq(cx, max(yx[,2]), by = dx),
  seq(cx, min(yx[,2]), by = -1*dx)[-1]) %>% 
  sort()
g <- expand_grid(
  y = vy,
  x = vx) %>% 
  mutate(
    geom = map2(x, y, function(x, y){
      dx2 <- dx/2
      dy2 <- dy/2
      
      # y = 90; x = 60
      p <- tribble(
        ~y, ~x, 
        y - dy2, x - dx2,      # lower left
        y + dy2, x + dx2) %>%  # upper right
        st_as_sf(
          coords = c("y", "x"), 
          crs    = st_crs("+proj=calcofi")) %>% 
        st_bbox() %>% 
        st_as_sfc() %>% 
        st_transform(4326) %>% 
        .[[1]]
    })) %>% 
  st_as_sf()
    
# g_0 <- g 
mapview(g)

shelf(leaflet)

gc <- g %>% 
  filter(
    y <= cy + dy*5,
    y >= cy - dy*5,
    x <= cx + dx*5,
    x >= cx - dx*5)

leaflet() %>% 
  addProviderTiles(providers$Esri.OceanBasemap) %>% 
  addPolygons(data = gc)


r <- terra::rast(
  xmin = min(vy), xmax = max(vy), 
  ymin = min(vx), ymax = max(vx), 
  ncols = length(vy), nrows = length(vx),
  nlyrs = 1, vals = NA,
  crs = "+proj=calcofi")
```

```{sql connection=con}
create extension postgis_raster;
CREATE TABLE test_rast(rid serial primary key, rast raster);
INSERT INTO test_rast(rid, rast)
 VALUES(3, ST_MakeEmptyRaster(100, 100, 0.0005, 0.0005, 1, 1, 0, 0, 4326) );
 -- Add another band of type 8 bit unsigned integer with pixels initialized to 200
UPDATE test_rast
  SET rast = ST_AddBand(rast,'8BUI'::text, 200)
  WHERE rid = 1;
  
  
```

```{r}
shelf("rpostgis")

pgPostGIS(con)
pgListGeom(con, geog = TRUE)
pgListRast(con)

r <- pgGetRast(con, "test_rast")

r


(crs_cc <- CRS("+proj=calcofi"))
pgSRID(con, crs_cc, create.srid = TRUE)
# No matches were found in spatial_ref_sys. New SRID created (880001)



tbl(con, "ctd_casts") %>% 
  group_by(longitude, latitude)

# ∆ 0.1, 5 (alongshore, offshore); ctr: 90, 60

# ∆ 0.1, 1 (alongshore, offshore); ctr: 90, 60



```
