---
title: "Ocean Dumping / Disposal"
author: "Ben Best"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
```

## Load


```{r}
# packages
if (!require("librarian")){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  dplyr, DT, glue, here, mapview, sf)
select <- dplyr::select
mapviewOptions(fgb = FALSE)
source(here::here("libs/db.R")) # defines variables: con, dir_gdrive
```


* [Ocean Disposal Sites | InPort](https://www.fisheries.noaa.gov/inport/item/54193)

```{r}
gpkg <- file.path(dir_gdrive, "data/US-ocean-disposal-sites/OceanDisposalSite.gpkg")
st_layers(gpkg)

dumps <- st_read(gpkg, "OCEANDISPOSALSITE") %>% 
  st_transform(4326)

stations <- st_read(con, "stations")
hull <- st_convex_hull(st_union(stations))

x <- st_intersects(dumps, hull, sparse = F)[,1]
dumps <- dumps[x,]
mapview(
  dumps)

dumps %>% 
  st_drop_geometry() %>% 
  datatable()
```
