---
title: "Load `field_labels` from Google Sheet"
author: "Ben Best"
date: "`r Sys.time()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
source(here::here("libs/rmd.R")) # defines function: time_it
knitr::opts_chunk$set(
  echo = TRUE, warning = F, message = F, time_chunk = TRUE)
```

## Load Google Sheet into `field_labels`

* Google Sheet: [field_labels | calcofi - Google Sheets](https://docs.google.com/spreadsheets/d/1ghM30pIdcsun7XWzLRKh4EilUplN60YdHayfiilPFwE/edit?pli=1#gid=0)

```{r field_labels}
# packages
source(here::here("libs/db.R")) # defines variables: con, dir_gdrive
librarian::shelf(
  googlesheets4, knitr, purrr)

# google sheet
gsheet <- "https://docs.google.com/spreadsheets/d/1ghM30pIdcsun7XWzLRKh4EilUplN60YdHayfiilPFwE/edit"

# no need to authenticate since shared for anyone to view
gs4_deauth() 

# read data
d <- read_sheet(gsheet)

# check that variables are globally unique
stopifnot(d$table_field %>% duplicated() %>% sum() == 0)

# check that table.variable exists in the database
d <- d %>% 
  # filter(active) %>% 
  mutate(
    tbl_exists = map_lgl(
      table_field, function(tbl_fld){
        # tbl_fld = "ctdcast_bottle.t_deg_c"
        x <- strsplit(tbl_fld, ".", fixed=T)[[1]]
        tbl <- x[1]
        fld <- x[2]
        tbl %in% dbListTables(con, tbl) }),
    fld_exists = map_lgl(
      table_field, function(tbl_fld){
        # tbl_fld = "ctdcast_bottle.t_deg_c"
        x <- strsplit(tbl_fld, ".", fixed=T)[[1]]
        tbl <- x[1]
        fld <- x[2]
        if (!tbl %in% dbListTables(con, tbl))
          return(FALSE)
        fld %in% dbListFields(con, tbl) }))
d %>% 
  filter(active) %>% 
  pull(fld_exists) %>% 
  stopifnot(all(.))

# write to database
d %>% 
  select(-tbl_exists, -fld_exists) %>% 
  dbWriteTable(con, "field_labels", ., overwrite=T)

# show table
kable(d)
```
