---
title: "Load Oceanographic Bottle & Cast Data, Plus DIC & Stations"
author: "Ben Best"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
source(here::here("libs/rmd.R")) # defines function: time_it
knitr::opts_chunk$set(
  echo = TRUE, warning = F, message = F, time_chunk = TRUE)
```

## Packages & setup

```{r packages}
source(here::here("libs/db.R")) # defines variables: con, dir_gdrive
librarian::shelf(
  glue, mapview, purrr, readr, readxl, sf, skimr, stringr, tidyr)
options(readr.show_col_types = F)
mapviewOptions(fgb = FALSE)

# helper functions ----

# convert station ID to lon, lat using the proj library
proj <- "/Users/bbest/homebrew/bin/proj" # installed on Ben's MacBookPro from https://proj.org/apps/proj.html
lonlat_to_stationid <- function(lon, lat){
  system(glue("echo {lon} {lat} | {proj} +proj=calcofi +epsg=4326 -f '%05.1f'"), intern=T) %>%
    stringr::str_replace("\t", " ")
}
stationid_to_lonlat <- function(stationid){
  # using 5th decimal place, a la CCE_Stations.txt
  system(glue("echo {stationid} | {proj} +proj=calcofi +epsg=4326  -I -d 5"), intern=T) %>%
    stringr::str_replace("\t", " ")
}
# (a_staid  <- stations$Sta_ID[1]) # "001.0 168.0"
# (a_lonlat <- stationid_to_lonlat(a_staid)) # 93.3	26.7
# a_lon <- str_split(a_lonlat, " ", simplify=T)[1] %>% as.double()
# a_lat <- str_split(a_lonlat, " ", simplify=T)[2] %>% as.double()
# lonlat_to_stationid(a_lon, a_lat) # "1.00 168.00" -> "001.0 168.0"
# "1.0 168.0"
```

## Load into Database

Initial copy from `CalCOFI/calcofi4r:data-raw/`[`bottle.R`](https://github.com/CalCOFI/calcofi4r/blob/bc8427670fb474390326a054bda9c10cf6de1831/data-raw/bottle.R).

```{r paths}
# paths ----

# oceanographic source paths
bottle_csv <- file.path(dir_gdrive, "data/oceanographic-data/bottle-database/CalCOFI_Database_194903-202001_csv_22Sep2021/194903-202001_Bottle.csv")
cast_csv   <- file.path(dir_gdrive, "data/oceanographic-data/bottle-database/CalCOFI_Database_194903-202001_csv_22Sep2021/194903-202001_Cast.csv")
# bottle_cast_rds <- file.path(dir_gdrive, "data/oceanographic-data/bottle-database/bottle_cast.rds")
DIC_csv    <- file.path(dir_gdrive, "data/DIC/CalCOFI_DICs_200901-201507_28June2018.csv")

# stations source paths
# source: Shonna Dovel <sdovel@ucsd.edu> 2022-03-17
stations_ccelter_xls <- file.path(dir_gdrive, "data/CalCOFI-stations/CalCOFI station LatLong.xlsx")
# sourc: http://cce.lternet.edu/data/gmt-mapper
stations_cce_txt     <- file.path(dir_gdrive, "data/CalCOFI-stations/CCE_Stations.txt")
stations_sccoos_txt  <- file.path(dir_gdrive, "data/CalCOFI-stations/SCCOOS_Stations.txt")

# study area destination paths
calcofi_geo           <- here("data/calcofi_oceano-bottle-stations_convex-hull.geojson")
calcofi_offshore_geo  <- here("data/calcofi_oceano-bottle-stations_convex-hull_offshore.geojson")
calcofi_nearshore_geo <- here("data/calcofi_oceano-bottle-stations_convex-hull_nearshore.geojson")

# check paths
stopifnot(all(file.exists(
  bottle_csv, cast_csv, DIC_csv,
  stations_ccelter_xls, stations_cce_txt, stations_sccoos_txt)))

# read csv sources ----

d_bottle <- read_csv(bottle_csv, skip=1, col_names = F, guess_max = 1000000)
#d_bottle_problems() <- problems()
names(d_bottle) <- str_split(
  readLines(bottle_csv, n=1), ",")[[1]] %>%
  str_replace("\xb5", "µ")

d_cast  <- read_csv(cast_csv)

d_DIC <- read_csv(DIC_csv, skip=1, col_names = F, guess_max = 1000000)
names(d_DIC) <- str_split(
  readLines(DIC_csv, n=1), ",")[[1]] %>%
  str_replace("\xb5", "µ")
# d_DIC %>% head() %>% View()
d_DIC <- d_DIC %>%
  rename("Sta_ID"="Line Sta_ID")
```

## `stations`

```{r stations}
# get unique station IDs from the casts
stations <- d_cast %>%
  select(Sta_ID) %>%
  group_by(Sta_ID) %>%
  summarize() %>%
  mutate(
    is_cast     = TRUE,
    lonlat_proj = map_chr(Sta_ID, stationid_to_lonlat)) %>%
  separate(lonlat_proj, c("lon", "lat"), sep=" ", convert = T) %>%
  separate(
    Sta_ID, c("Sta_ID_line", "Sta_ID_station"), sep=" ", remove=F, convert=T) %>%
  mutate(
    offshore = ifelse(Sta_ID_station > 60, T, F)) %>%
  st_as_sf(
    coords = c("lon", "lat"), crs=4326, remove = F)
# stations$Sta_ID
# mapview(stations)

# + CCE column ----
stations_cce <- read_tsv(stations_cce_txt, skip = 2) %>%
  mutate(
    is_cce = TRUE,
    Sta_ID = map2_chr(LonDec, LatDec, lonlat_to_stationid))
stopifnot(sum(!stations_cce$Sta_ID %in% stations$Sta_ID) == 0)
stations <- stations %>%
  left_join(
    stations_cce %>%
      select(Sta_ID, is_cce),
    by = "Sta_ID")

# + CCE-LTER column ----
stations_ccelter <- read_excel(stations_ccelter_xls) %>%
  mutate(
    is_ccelter = TRUE,
    Sta_ID       = glue("{sprintf('%05.1f', Line)} {sprintf('%05.1f', Sta)}"),
    lonlat_proj  = map_chr(Sta_ID, stationid_to_lonlat)) %>%
  separate(
    lonlat_proj, c("lon", "lat"), sep=" ", convert = T) %>%
  select(Sta_ID, is_ccelter, lon, lon_0 = `Lon Dec`, lat, lat_0 = `Lat Dec`)
# stations_ccelter %>% View()

stopifnot(sum(!stations_ccelter$Sta_ID %in% stations$Sta_ID) == 0)
stations <- stations %>%
  left_join(
    stations_ccelter %>%
      select(Sta_ID, is_ccelter),
    by = "Sta_ID")

# + SCCOOS column ----
stations_sccoos <- read_tsv(stations_sccoos_txt) %>%
  mutate(
    is_sccoos = TRUE,
    Sta_ID = map2_chr(LonDec, LatDec, lonlat_to_stationid))
stopifnot(sum(!stations_sccoos$Sta_ID %in% stations$Sta_ID) == 0)
stations <- stations %>%
  left_join(
    stations_sccoos %>%
      select(Sta_ID, is_sccoos),
    by = "Sta_ID")

# stations_0 <- stations
stations <- stations %>% 
  mutate(across(where(is.logical), ~replace_na(.,FALSE)))

stations %>%
  select(is_cce, is_ccelter) %>%
  st_drop_geometry() %>%
  table(useNA = "ifany")
#           is_cce
# is_ccelter FALSE TRUE
#      FALSE  2521   47
#      TRUE      0   66
# So: 47 extra stations in CCE that are missing in  CCE-LTER
stations %>%
  select(is_cce, is_sccoos) %>%
  st_drop_geometry() %>%
  table(useNA = "ifany")
#        is_sccoos
# is_cce  FALSE TRUE
#   FALSE  2521    0
#   TRUE    104    9
# So: only 9 stations in SCCOS, none of which are in CCE

# column order ----
stations <- stations %>%
  select(
    Sta_ID, Sta_ID_line, Sta_ID_station,
    lon, lat,
    offshore,
    is_cast, is_cce, is_ccelter, is_sccoos) %>% 
  rename(geom = geometry)

st_write(stations, con, "stations")
# to get to show as layer in tile.calcofi.io
DBI::dbSendQuery(con, "SELECT UpdateGeometrySRID('stations', 'geom', 4326);")

mapview(stations)
stations %>% 
  st_drop_geometry() %>% 
  skim()
```

## `cast`

```{r cast}
stopifnot(length(setdiff(unique(d_cast$Sta_ID), stations$Sta_ID)) == 0)

d_cast <- d_cast %>% 
  mutate(
    Date = lubridate::as_date(Date, format = "%m/%d/%Y")) %>%
  st_as_sf(
    coords = c("Lon_Dec", "Lat_Dec"), crs=4326, remove = F) %>%
  rename(geom = geometry)

st_write(d_cast, con, "cast")
# to get to show as layer in tile.calcofi.io
dbSendQuery(con, "SELECT UpdateGeometrySRID('cast', 'geom', 4326);")
d_cast %>% 
  st_drop_geometry() %>% 
  skim()
```

## `cast_bottle`

```{r cast_bottle}
dbWriteTable(con, "cast_bottle", d_bottle, overwrite=T)
skim(d_bottle)
```

## `cast_bottle_dic`

```{r cast_bottle_dic}
# ensure bottle.Btl_Cnt is unique in 
stopifnot(d_bottle$Btl_Cnt %>% duplicated() %>% sum() == 0)

# ensure uniquely matchable to cast_bottle
x <- anti_join(
  d_DIC,
  d_bottle, 
  by=c(
    "Bottle_Index" = "Btl_Cnt"))
stopifnot(nrow(x) == 0)

d_DIC <- d_DIC %>% 
  rename(
    Cst_Cnt = Cast_Index,
    Btl_Cnt = Bottle_Index)

dbWriteTable(con, "cast_bottle_dic", d_DIC, overwrite=T)
skim(d_DIC)
```
