---
config:
  layout: elk
---
erDiagram
    sonobuoy_deployment {
        varchar deployment_key PK
        varchar cruise_label
        varchar sonobuoy_label
        varchar sonobuoy_type
        double line
        double station
        varchar site_key
        double latitude
        double longitude
        timestamp datetime_start_utc
        int n_hours
        geometry geom
        varchar grid_key
        varchar cruise_key
    }
    sonobuoy_scan {
        int scan_id PK
        varchar cruise_label
        varchar season
        varchar sonobuoy_label
        varchar deployment_key FK
        varchar sonobuoy_type
        double line_raw
        double line
        double station
        varchar date_raw
        varchar hour_raw
        timestamp datetime_start_utc
        varchar recording_quality
        varchar background_level
        varchar background_types
        varchar detections_flag
        varchar species_detected_raw
        int blue_b
        int blue_d
        int fin_20hz_singular
        int fin_20hz_song
        int fin_cc
        int fin_hc
        int humpback_song
        int humpback_nonsong
        varchar start_end_note
        double hour_span
        varchar comments
        varchar scan_method
        varchar time_window
        varchar freq_top
        varchar freq_low
        double fft_length
        varchar fft_overlap
        varchar site_key
        double longitude
        double latitude
        geometry geom
        varchar grid_key
        varchar cruise_key
    }
    dataset {
        varchar provider
        varchar dataset
        varchar dataset_name
        varchar dataset_name_short
        varchar category
        varchar color
        varchar description
        varchar citation_main
        varchar citation_others
        varchar link_calcofi_org
        varchar link_data_source
        varchar link_others
        varchar tables
        varchar coverage_temporal
        varchar coverage_spatial
        varchar license
        varchar pi_names
        varchar doi
        varchar license_url
        varchar acknowledgement
        varchar contact
    }
    sonobuoy_deployment ||--o{ sonobuoy_scan : "deployment_key"
    classDef lightblue stroke:#ADD8E6,stroke-width:3px
    class sonobuoy_deployment,sonobuoy_scan lightblue
    classDef white stroke:#FFFFFF,stroke-width:3px
    class dataset white
