-- ----------------------------------------------------------
-- MDB Tools - A library for reading MS Access database files
-- Copyright (C) 2000-2011 Brian Bruns and others.
-- Files in libmdb are licensed under LGPL and the utilities under
-- the GPL, see COPYING.LIB and COPYING files respectively.
-- Check out http://mdbtools.sourceforge.net
-- ----------------------------------------------------------

-- That file uses encoding UTF-8

CREATE TABLE [0-Cast & Zooplankton_Notes]
 (
	[Edit]			Integer, 
	[Changed]			Text (255), 
	[Comments]			Text (255), 
	[Tow Sheet Doc Name]			Text (255)
);

CREATE TABLE [0-Categories]
 (
	[Table_Name]			Text (50), 
	[Field_Name]			Text (50), 
	[Units]			Text (50), 
	[Values]			Memo/Hyperlink (255), 
	[Description]			Memo/Hyperlink (255)
);

CREATE TABLE [0-Field Descriptions]
 (
	[Table_Name]			Text (255), 
	[Field_Name]			Text (255), 
	[Units]			Text (255), 
	[Values]			Text (255), 
	[Description]			Text (255), 
	[Index]			Long Integer
);

CREATE TABLE [0-Measurements]
 (
	[Name]			Text (50), 
	[Units]			Text (50), 
	[Accuracy]			Text (50), 
	[Description]			Text (50), 
	[Year_started]			DateTime NOT NULL, 
	[Year_ended]			DateTime, 
	[Method]			Memo/Hyperlink (255)
);

CREATE TABLE [0-Query Info]
 (
	[Name]			Text (50), 
	[Purpose]			Memo/Hyperlink (255), 
	[Date - created]			DateTime, 
	[Date - modified]			DateTime, 
	[Comments]			Memo/Hyperlink (255)
);

CREATE TABLE [0-Ships]
 (
	[ID]			Long Integer, 
	[Ship_Code]			Text (50), 
	[Country_Code]			Integer, 
	[Ship]			Text (50), 
	[Ship_Name]			Text (50), 
	[Operator]			Text (50)
);

CREATE TABLE [0-Tables Info]
 (
	[Name]			Text (50), 
	[Purpose]			Memo/Hyperlink (255)
);

CREATE TABLE [0-Units]
 (
	[Unit Symbol]			Text (50), 
	[Unit Description]			Text (120)
);

CREATE TABLE [0-Work Done]
 (
	[Date]			DateTime, 
	[Note]			Memo/Hyperlink (255), 
	[Initial]			Text (50)
);

CREATE TABLE [2304Add2DB-cast]
 (
	[Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (255), 
	[Cruise]			Long Integer, 
	[Cruz_Sta]			Double, 
	[DbSta_ID]			Long Integer, 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Text (255), 
	[Date]			DateTime, 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			DateTime, 
	[Lat_Dec]			Text (255), 
	[Lat_Deg]			Text (255), 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Text (255), 
	[Lon_Deg]			Text (255), 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Text (255), 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Text (255), 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Wave_Dir]			Text (255), 
	[Wave_Ht]			Text (255), 
	[Wave_Prd]			Text (255), 
	[Wind_Dir]			Long Integer, 
	[Wind_Spd]			Long Integer, 
	[Barometer]			Double, 
	[Dry_T]			Double, 
	[Wet_T]			Double, 
	[Wea]			Text (255), 
	[Cloud_Typ]			Text (255), 
	[Cloud_Amt]			Text (255), 
	[Visibility]			Text (255), 
	[Secchi]			Text (255), 
	[ForelU]			Text (255), 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Long Integer, 
	[Event_Num]			Long Integer, 
	[Cruz_ID]			Text (255), 
	[Cruz_Leg]			Long Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Long Integer, 
	[Cruz_Num]			Long Integer, 
	[IntChl]			Double, 
	[IntPha]			Text (255), 
	[Inc_Str]			Text (255), 
	[Inc_End]			Text (255), 
	[PST_LAN]			Text (255), 
	[Civil_T]			Text (255), 
	[Timezone]			Text (255), 
	[IntC14]			Text (255)
);

CREATE TABLE [2304Add2DB-cast_ImportErrors]
 (
	[Error]			Text (255), 
	[Field]			Text (255), 
	[Row]			Long Integer
);

CREATE TABLE [Anom_ISL_1_Jen_all]
 (
	[Cruise]			Long Integer, 
	[Code_Region]			Text (255), 
	[Code-SCB]			Text (50), 
	[Code-Nearshore]			Text (50), 
	[Sta_ID]			Text (255), 
	[St_Line]			Single, 
	[St_Sta]			Single, 
	[Distance]			Single, 
	[Cast_ID]			Text (255), 
	[Year]			Long Integer, 
	[Quarter]			Long Integer, 
	[YearValue]			Double, 
	[Date]			Double, 
	[Julian_Day]			Double, 
	[Time]			Double, 
	[Depth]			Double, 
	[Temp]			Double, 
	[Sal]			Double, 
	[Density]			Double, 
	[O2]			Double, 
	[NO3]			Single, 
	[PO4]			Single, 
	[SiO3]			Single, 
	[O2Sat]			Double, 
	[Chla]			Double, 
	[TempStDev]			Double, 
	[SalStDev]			Double, 
	[DensStDev]			Double, 
	[O2StDev]			Double, 
	[O2SatStDev]			Double, 
	[ChlaStDev]			Double, 
	[NO3StDev]			Double, 
	[NO2StDev]			Double, 
	[PO4StDev]			Double, 
	[SiO3StDev]			Double, 
	[TempAnom]			Double, 
	[SalAnom]			Double, 
	[DensAnom]			Double, 
	[O2Anom]			Double, 
	[O2SatAnom]			Double, 
	[ChlaAnom]			Double, 
	[NO3Anom]			Double, 
	[PO4Anom]			Double, 
	[SIO3Anom]			Double, 
	[TempStAnom]			Double, 
	[SalStAnom]			Double, 
	[DensStAnom]			Double, 
	[O2StAnom]			Double, 
	[O2SatStAnom]			Double, 
	[ChlaStAnom]			Double, 
	[NO3StAnom]			Double, 
	[PO4StAnom]			Double, 
	[SiO3StAnom]			Double, 
	[Spice]			Text (255), 
	[NStar]			Double
);

CREATE TABLE [Bottle]
 (
	[Cst_Cnt]			Long Integer, 
	[Btl_Cnt]			Long Integer NOT NULL, 
	[Sta_ID]			Text (255), 
	[Depth_ID]			Text (255), 
	[Depthm]			Integer, 
	[T_degC]			Single, 
	[Salnty]			Single, 
	[O2ml_L]			Single, 
	[STheta]			Single, 
	[O2Sat]			Single, 
	[Oxy_µmol/Kg]			Single, 
	[BtlNum]			Long Integer, 
	[RecInd]			Integer
);

CREATE TABLE [Bottle_All_2105]
 (
	[Bottle_Cst_Cnt]			Long Integer, 
	[Bottle_Btl_Cnt]			Long Integer, 
	[Sta_ID]			Text (255), 
	[Depth_ID]			Text (255), 
	[Depthm]			Integer, 
	[T_degC]			Single, 
	[Salnty]			Single, 
	[O2ml_L]			Single, 
	[STheta]			Single, 
	[O2Sat]			Single, 
	[Oxy_µmol/Kg]			Single, 
	[BtlNum]			Long Integer, 
	[RecInd]			Integer, 
	[Bottle_Q_Btl_Cnt]			Long Integer, 
	[T_prec]			Integer, 
	[T_qual]			Integer, 
	[S_prec]			Integer, 
	[S_qual]			Integer, 
	[P_qual]			Integer, 
	[O_qual]			Integer, 
	[SThtaq]			Integer, 
	[O2Satq]			Integer, 
	[Chl_Btl_Cnt]			Long Integer, 
	[ChlorA]			Single, 
	[Chlqua]			Long Integer, 
	[Phaeop]			Single, 
	[Phaqua]			Long Integer, 
	[Nuts_Btl_Cnt]			Long Integer, 
	[PO4uM]			Single, 
	[PO4q]			Integer, 
	[SiO3uM]			Single, 
	[SiO3qu]			Integer, 
	[NO2uM]			Single, 
	[NO2q]			Integer, 
	[NO3uM]			Single, 
	[NO3q]			Integer, 
	[NH3uM]			Single, 
	[NH3q]			Integer, 
	[Prodo_Bottle_Cst_Cnt]			Long Integer, 
	[Prodo_Bottle_Btl_Cnt]			Long Integer, 
	[C14As1]			Single, 
	[C14A1p]			Integer, 
	[C14A1q]			Integer, 
	[C14As2]			Single, 
	[C14A2p]			Integer, 
	[C14A2q]			Integer, 
	[DarkAs]			Single, 
	[DarkAp]			Integer, 
	[DarkAq]			Integer, 
	[MeanAs]			Single, 
	[MeanAp]			Integer, 
	[MeanAq]			Integer, 
	[IncTim]			DateTime, 
	[LightP]			Single, 
	[R_PRES]			Integer, 
	[R_POTEMP]			Single, 
	[R_SVA]			Single, 
	[R_DYNHT]			Single, 
	[R_NH4]			Single, 
	[R_Oxy_µmol/Kg]			Single, 
	[DIC1]			Double, 
	[DIC2]			Double, 
	[TA1]			Double, 
	[TA2]			Double, 
	[pH1]			Double, 
	[pH2]			Double, 
	[DICs_Btl_Cnt]			Long Integer, 
	[DIC Quality Comment]			Text (255)
);

CREATE TABLE [Bottle_All_LTER_all]
 (
	[Bottle_Cst_Cnt]			Long Integer, 
	[Bottle_Btl_Cnt]			Long Integer, 
	[Sta_ID]			Text (255), 
	[Depth_ID]			Text (255), 
	[Depthm]			Integer, 
	[T_degC]			Single, 
	[Salnty]			Single, 
	[O2ml_L]			Single, 
	[STheta]			Single, 
	[O2Sat]			Single, 
	[Oxy_µmol/Kg]			Single, 
	[BtlNum]			Long Integer, 
	[RecInd]			Integer, 
	[Bottle_Q_Btl_Cnt]			Long Integer, 
	[T_prec]			Integer, 
	[T_qual]			Integer, 
	[S_prec]			Integer, 
	[S_qual]			Integer, 
	[P_qual]			Integer, 
	[O_qual]			Integer, 
	[SThtaq]			Integer, 
	[O2Satq]			Integer, 
	[Chl_Btl_Cnt]			Long Integer, 
	[ChlorA]			Single, 
	[Chlqua]			Long Integer, 
	[Phaeop]			Single, 
	[Phaqua]			Long Integer, 
	[Nuts_Btl_Cnt]			Long Integer, 
	[PO4uM]			Single, 
	[PO4q]			Integer, 
	[SiO3uM]			Single, 
	[SiO3qu]			Integer, 
	[NO2uM]			Single, 
	[NO2q]			Integer, 
	[NO3uM]			Single, 
	[NO3q]			Integer, 
	[NH3uM]			Single, 
	[NH3q]			Integer, 
	[Prodo_Bottle_Cst_Cnt]			Long Integer, 
	[Prodo_Bottle_Btl_Cnt]			Long Integer, 
	[C14As1]			Single, 
	[C14A1p]			Integer, 
	[C14A1q]			Integer, 
	[C14As2]			Single, 
	[C14A2p]			Integer, 
	[C14A2q]			Integer, 
	[DarkAs]			Single, 
	[DarkAp]			Integer, 
	[DarkAq]			Integer, 
	[MeanAs]			Single, 
	[MeanAp]			Integer, 
	[MeanAq]			Integer, 
	[IncTim]			DateTime, 
	[LightP]			Single, 
	[R_PRES]			Integer, 
	[R_POTEMP]			Single, 
	[R_SVA]			Single, 
	[R_DYNHT]			Single, 
	[R_NH4]			Single, 
	[R_Oxy_µmol/Kg]			Single, 
	[DIC1]			Double, 
	[DIC2]			Double, 
	[TA1]			Double, 
	[TA2]			Double, 
	[pH1]			Double, 
	[pH2]			Double, 
	[DICs_Btl_Cnt]			Long Integer, 
	[DIC Quality Comment]			Text (255)
);

CREATE TABLE [Bottle_Q]
 (
	[Btl_Cnt]			Long Integer NOT NULL, 
	[T_prec]			Integer, 
	[T_qual]			Integer, 
	[S_prec]			Integer, 
	[S_qual]			Integer, 
	[P_qual]			Integer, 
	[O_qual]			Integer, 
	[SThtaq]			Integer, 
	[O2Satq]			Integer
);

CREATE TABLE [BottleData_194903_202304]
 (
	[Cast_Num]			Text (255), 
	[Btl_Num]			Long Integer, 
	[Cst_Cnt]			Long Integer, 
	[Cruise]			Long Integer, 
	[Order_Occ]			Integer, 
	[Date]			DateTime, 
	[Time]			DateTime, 
	[DateTime]			DateTime, 
	[St_Line]			Double, 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Sta_Code]			Text (255), 
	[Lat_Dec]			Double, 
	[Lon_Dec]			Double, 
	[Distance]			Single, 
	[Btl_Cnt]			Long Integer, 
	[BtlNum]			Long Integer, 
	[Depthm]			Integer, 
	[T_degC]			Single, 
	[Salnty]			Single, 
	[STheta]			Single, 
	[O2ml_L]			Single, 
	[O2Sat]			Single, 
	[PO4uM]			Single, 
	[SiO3uM]			Single, 
	[NO3uM]			Single, 
	[NH3uM]			Single, 
	[ChlorA]			Single, 
	[Phaeop]			Single, 
	[RecInd]			Integer
);

CREATE TABLE [Bottles Per Cast]
 (
	[Cast_ID]			Text (255), 
	[CountOfCst_Cnt]			Long Integer, 
	[CountOfBtl_Cnt]			Long Integer, 
	[Cst_Cnt]			Long Integer
);

CREATE TABLE [Cast]
 (
	[Cst_Cnt]			Long Integer NOT NULL, 
	[Cruise_ID]			Text (50), 
	[Cruise]			Long Integer, 
	[CruiseAlias]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Single, 
	[Date]			DateTime, 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			DateTime, 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Secchi]			Integer, 
	[ForelU]			Integer, 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Integer, 
	[Event_Num]			Integer, 
	[Cruz_Leg]			Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Single, 
	[IntC14]			Single
);

CREATE TABLE [Cast_2105]
 (
	[Cast_Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (50), 
	[Cruise]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Single, 
	[Date]			Text (255), 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Cast_Secchi]			Integer, 
	[Cast_ForelU]			Integer, 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Integer, 
	[Event_Num]			Integer, 
	[Cruz_Leg]			Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Single, 
	[Cast_IntC14]			Single, 
	[Prodo_Cast_Cst_Cnt]			Long Integer, 
	[Inc_Str]			DateTime, 
	[Inc_End]			DateTime, 
	[PST_LAN]			DateTime, 
	[Civil_T]			DateTime, 
	[TimeZone]			Text (255), 
	[Prodo_Cast_IntC14]			Single, 
	[Weather_Cst_Cnt]			Long Integer, 
	[Wave_Dir]			Integer, 
	[Wave_Ht]			Integer, 
	[Wave_Prd]			Integer, 
	[Wind_Dir]			Integer, 
	[Wind_Spd]			Integer, 
	[Barometer]			Single, 
	[Dry_T]			Single, 
	[Wet_T]			Single, 
	[Wea]			Integer, 
	[Cloud_Typ]			Integer, 
	[Cloud_Amt]			Integer, 
	[Visibility]			Integer, 
	[Weather_Secchi]			Integer, 
	[Weather_ForelU]			Integer
);

CREATE TABLE [Cast_All_LTER_all]
 (
	[Cast_Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (50), 
	[Cruise]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Single, 
	[Date]			Text (255), 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Cast_Secchi]			Integer, 
	[Cast_ForelU]			Integer, 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Integer, 
	[Event_Num]			Integer, 
	[Cruz_Leg]			Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Single, 
	[Cast_IntC14]			Single, 
	[Prodo_Cast_Cst_Cnt]			Long Integer, 
	[Inc_Str]			DateTime, 
	[Inc_End]			DateTime, 
	[PST_LAN]			DateTime, 
	[Civil_T]			DateTime, 
	[TimeZone]			Text (255), 
	[Prodo_Cast_IntC14]			Single, 
	[Weather_Cst_Cnt]			Long Integer, 
	[Wave_Dir]			Integer, 
	[Wave_Ht]			Integer, 
	[Wave_Prd]			Integer, 
	[Wind_Dir]			Integer, 
	[Wind_Spd]			Integer, 
	[Barometer]			Single, 
	[Dry_T]			Single, 
	[Wet_T]			Single, 
	[Wea]			Integer, 
	[Cloud_Typ]			Integer, 
	[Cloud_Amt]			Integer, 
	[Visibility]			Integer, 
	[Weather_Secchi]			Integer, 
	[Weather_ForelU]			Integer
);

CREATE TABLE [Cast_not_org]
 (
	[Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (255), 
	[Cruise]			Long Integer, 
	[CruiseAlias]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Text (255), 
	[Date]			DateTime, 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Long Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Long Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Text (255), 
	[Secchi]			Text (255), 
	[ForelU]			Text (255), 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Text (255), 
	[Event_Num]			Long Integer, 
	[Cruz_Leg]			Text (255), 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Text (255), 
	[IntC14]			Text (255)
);

CREATE TABLE [Cast_test]
 (
	[Cast_Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (50), 
	[Cruise]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Single, 
	[Date]			Text (255), 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Cast_Secchi]			Integer, 
	[Cast_ForelU]			Integer, 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Integer, 
	[Event_Num]			Integer, 
	[Cruz_Leg]			Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Single, 
	[Cast_IntC14]			Single, 
	[Prodo_Cast_Cst_Cnt]			Long Integer, 
	[Inc_Str]			DateTime, 
	[Inc_End]			DateTime, 
	[PST_LAN]			DateTime, 
	[Civil_T]			DateTime, 
	[TimeZone]			Text (255), 
	[Prodo_Cast_IntC14]			Single, 
	[Weather_Cst_Cnt]			Long Integer, 
	[Wave_Dir]			Integer, 
	[Wave_Ht]			Integer, 
	[Wave_Prd]			Integer, 
	[Wind_Dir]			Integer, 
	[Wind_Spd]			Integer, 
	[Barometer]			Single, 
	[Dry_T]			Single, 
	[Wet_T]			Single, 
	[Wea]			Integer, 
	[Cloud_Typ]			Integer, 
	[Cloud_Amt]			Integer, 
	[Visibility]			Integer, 
	[Weather_Secchi]			Integer, 
	[Weather_ForelU]			Integer
);

CREATE TABLE [Chl]
 (
	[Btl_Cnt]			Long Integer NOT NULL, 
	[ChlorA]			Single, 
	[Chlqua]			Long Integer, 
	[Phaeop]			Single, 
	[Phaqua]			Long Integer
);

CREATE TABLE [Copy of 2301Add2DB-cast_rcl]
 (
	[Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (255), 
	[Cruise]			Long Integer, 
	[Cruz_Sta]			Double, 
	[DbSta_ID]			Long Integer, 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Double, 
	[Date]			DateTime, 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			DateTime, 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Long Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Long Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Double, 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Double, 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Wave_Dir]			Text (255), 
	[Wave_Ht]			Text (255), 
	[Wave_Prd]			Text (255), 
	[Wind_Dir]			Long Integer, 
	[Wind_Spd]			Long Integer, 
	[Barometer]			Double, 
	[Dry_T]			Text (255), 
	[Wet_T]			Text (255), 
	[Wea]			Text (255), 
	[Cloud_Typ]			Text (255), 
	[Cloud_Amt]			Text (255), 
	[Visibility]			Text (255), 
	[Secchi]			Text (255), 
	[ForelU]			Text (255), 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Long Integer, 
	[Event_Num]			Long Integer, 
	[Cruz_ID]			Text (255), 
	[Cruz_Leg]			Long Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Long Integer, 
	[Cruz_Num]			Long Integer, 
	[IntChl]			Double, 
	[IntPha]			Text (255), 
	[Inc_Str]			Text (255), 
	[Inc_End]			Text (255), 
	[PST_LAN]			Text (255), 
	[Civil_T]			Text (255), 
	[Timezone]			Text (255), 
	[IntC14]			Text (255)
);

CREATE TABLE [Copy Of Bottle]
 (
	[Cst_Cnt]			Long Integer, 
	[Btl_Cnt]			Long Integer NOT NULL, 
	[Sta_ID]			Text (255), 
	[Depth_ID]			Text (255), 
	[Depthm]			Integer, 
	[T_degC]			Single, 
	[Salnty]			Single, 
	[O2ml_L]			Single, 
	[STheta]			Single, 
	[O2Sat]			Single, 
	[Oxy_µmol/Kg]			Single, 
	[BtlNum]			Long Integer, 
	[RecInd]			Integer
);

CREATE TABLE [CurrentStations]
 (
	[Sta_ID]			Text (255), 
	[Rpt_Line]			Text (255), 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[St_Line]			Double, 
	[Avg_Depth]			Long Integer, 
	[DBSta_ID]			Text (255)
);

CREATE TABLE [DICs]
 (
	[ID]			Long Integer, 
	[Cruise]			Long Integer, 
	[Btl_Cnt]			Long Integer, 
	[Bottle_ID1]			Long Integer, 
	[Bottle_ID2]			Long Integer, 
	[Niskin]			Long Integer, 
	[StaPr]			Double, 
	[Depthm]			Long Integer, 
	[Depth_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[pH1]			Double, 
	[pH2]			Double, 
	[DIC1]			Double, 
	[DIC2]			Double, 
	[TA1]			Double, 
	[TA2]			Double, 
	[Salinity1]			Double, 
	[Salinity2]			Double, 
	[Comments]			Text (255), 
	[Proposed Changes]			Text (255), 
	[DIC Quality Comment]			Text (255)
);

CREATE TABLE [HarmCoeffBottle]
 (
	[ID]			Long Integer, 
	[Sta_ID]			Text (255), 
	[StDepth]			Double, 
	[TempMean]			Double, 
	[TempAmpl]			Double, 
	[TempFreq]			Double, 
	[TempPhase]			Double, 
	[TempStDev]			Double, 
	[SalMean]			Double, 
	[SalAmpl]			Double, 
	[SalFreq]			Double, 
	[SalPhase]			Double, 
	[SalStDev]			Double, 
	[SigMean]			Double, 
	[SigAmpl]			Double, 
	[SigFreq]			Double, 
	[SigPhase]			Double, 
	[SigStDev]			Double, 
	[O2Mean]			Double, 
	[O2Ampl]			Double, 
	[O2Freq]			Double, 
	[O2Phase]			Double, 
	[O2StDev]			Double, 
	[O2SatMean]			Double, 
	[O2SatAmpl]			Double, 
	[O2SatFreq]			Double, 
	[O2SatPhase]			Double, 
	[O2SatStDev]			Double, 
	[ChlaMean]			Double, 
	[ChlaAmpl]			Double, 
	[ChlaFreq]			Double, 
	[ChlaPhase]			Double, 
	[ChlaStDev]			Double, 
	[NO3Mean]			Double, 
	[NO3Ampl]			Double, 
	[NO3Freq]			Double, 
	[NO3Phase]			Double, 
	[NO3StDev]			Double, 
	[NO2Mean]			Double, 
	[NO2Ampl]			Double, 
	[NO2Freq]			Double, 
	[NO2Phase]			Double, 
	[NO2StDev]			Double, 
	[PO4Mean]			Double, 
	[PO4Ampl]			Double, 
	[PO4Freq]			Double, 
	[PO4Phase]			Double, 
	[PO4StDev]			Double, 
	[SiO3Mean]			Double, 
	[SiO3Ampl]			Double, 
	[SiO3Freq]			Double, 
	[SiO3Phase]			Double, 
	[SiO3StDev]			Double
);

CREATE TABLE [HarmCoeffChla]
 (
	[Sta_ID]			Text (255), 
	[StDepth]			Double, 
	[ChlMean]			Double, 
	[ChlAmpl]			Double, 
	[ChlFreq]			Double, 
	[ChlPhase]			Double, 
	[LChlMean]			Double, 
	[LChlAmpl]			Double, 
	[LChlFreq]			Double, 
	[LChlPhase]			Double
);

CREATE TABLE [HarmCoeffLogZoo]
 (
	[Sta_ID]			Text (255), 
	[StationNO]			Double, 
	[LSmZooMean]			Double, 
	[LSmZooAmpl]			Double, 
	[LSmZooFreq]			Double, 
	[LSmZooPhase]			Double, 
	[ResNorm]			Double, 
	[ExitFlag]			Double
);

CREATE TABLE [HarmCoeffSigma]
 (
	[ID]			Long Integer, 
	[Sta_ID]			Text (255), 
	[StSigma]			Double, 
	[DepthMean]			Double, 
	[DepthAmpl]			Double, 
	[DepthFreq]			Double, 
	[DepthPhase]			Double, 
	[DepthStDev]			Double, 
	[TempMean]			Double, 
	[TempAmpl]			Double, 
	[TempFreq]			Double, 
	[TempPhase]			Double, 
	[TempStDev]			Double, 
	[SalMean]			Double, 
	[SalAmpl]			Double, 
	[SalFreq]			Double, 
	[SalPhase]			Double, 
	[SalStDev]			Double, 
	[O2Mean]			Double, 
	[O2Ampl]			Double, 
	[O2Freq]			Double, 
	[O2Phase]			Double, 
	[O2StDev]			Double, 
	[NO3Mean]			Double, 
	[NO3Ampl]			Double, 
	[NO3Freq]			Double, 
	[NO3Phase]			Double, 
	[NO3StDev]			Double, 
	[NO2Mean]			Double, 
	[NO2Ampl]			Double, 
	[NO2Freq]			Double, 
	[NO2Phase]			Double, 
	[NO2StDev]			Double, 
	[PO4Mean]			Double, 
	[PO4Ampl]			Double, 
	[PO4Freq]			Double, 
	[PO4Phase]			Double, 
	[PO4StDev]			Double, 
	[SiO3Mean]			Double, 
	[SiO3Ampl]			Double, 
	[SiO3Freq]			Double, 
	[SiO3Phase]			Double, 
	[SiO3StDev]			Double
);

CREATE TABLE [Mati_Hydro_1902-2107_finalthru2001]
 (
	[Cruise]			Long Integer, 
	[Sta_ID]			Text (255), 
	[Depthm]			Integer, 
	[T_degC]			Single, 
	[Salnty]			Single, 
	[O2ml_L]			Single, 
	[ChlorA]			Single, 
	[Phaeop]			Single, 
	[PO4uM]			Single, 
	[SiO3uM]			Single, 
	[NO2uM]			Single, 
	[NO3uM]			Single, 
	[NH3uM]			Single, 
	[Cst_Cnt]			Long Integer, 
	[Btl_Cnt]			Long Integer, 
	[STheta]			Single, 
	[O2Sat]			Single, 
	[Oxy_µmol/Kg]			Single
);

CREATE TABLE [Mati_Hydro_201902-202101]
 (
	[Cruise]			Long Integer, 
	[Sta_ID]			Text (255), 
	[Depthm]			Integer, 
	[T_degC]			Single, 
	[Salnty]			Single, 
	[O2ml_L]			Single, 
	[ChlorA]			Single, 
	[Phaeop]			Single, 
	[PO4uM]			Single, 
	[SiO3uM]			Single, 
	[NO2uM]			Single, 
	[NO3uM]			Single, 
	[NH3uM]			Single, 
	[Cst_Cnt]			Long Integer, 
	[Btl_Cnt]			Long Integer NOT NULL, 
	[STheta]			Single, 
	[O2Sat]			Single, 
	[Oxy_µmol/Kg]			Single
);

CREATE TABLE [Mati_Meta_1902-2107_finalthru2001]
 (
	[Cst_Cnt]			Long Integer NOT NULL, 
	[Cruise_ID]			Text (50), 
	[Cruise]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Single, 
	[Date]			Text (255), 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Integer, 
	[Event_Num]			Integer, 
	[Cruz_Leg]			Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Single, 
	[IntC14]			Single, 
	[Inc_Str]			DateTime, 
	[Inc_End]			DateTime, 
	[PST_LAN]			DateTime, 
	[Civil_T]			DateTime, 
	[TimeZone]			Text (255), 
	[Wave_Dir]			Integer, 
	[Wave_Ht]			Integer, 
	[Wave_Prd]			Integer, 
	[Wind_Dir]			Integer, 
	[Wind_Spd]			Integer, 
	[Barometer]			Single, 
	[Dry_T]			Single, 
	[Wet_T]			Single, 
	[Wea]			Integer, 
	[Cloud_Typ]			Integer, 
	[Cloud_Amt]			Integer, 
	[Visibility]			Integer, 
	[Secchi]			Integer, 
	[ForelU]			Integer
);

CREATE TABLE [Mati_Meta_201902-202101]
 (
	[Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (50), 
	[Cruise]			Long Integer, 
	[CruiseAlias]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Single, 
	[Date]			Text (255), 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Secchi]			Integer, 
	[ForelU]			Integer, 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Integer, 
	[Event_Num]			Integer, 
	[Cruz_Leg]			Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Single, 
	[IntC14]			Single
);

CREATE TABLE [Mati_Meta_201902-202208]
 (
	[Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (50), 
	[Cruise]			Long Integer, 
	[CruiseAlias]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Single, 
	[Date]			Text (255), 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Secchi]			Integer, 
	[ForelU]			Integer, 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Integer, 
	[Event_Num]			Integer, 
	[Cruz_Leg]			Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Single, 
	[IntC14]			Single
);

CREATE TABLE [Mati_Meta_2111_finalthru2001]
 (
	[Cst_Cnt]			Long Integer NOT NULL, 
	[Cruise_ID]			Text (50), 
	[Cruise]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Single, 
	[Date]			Text (255), 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Long Integer, 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Integer, 
	[Event_Num]			Integer, 
	[Cruz_Leg]			Integer, 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Single, 
	[IntC14]			Single, 
	[Inc_Str]			DateTime, 
	[Inc_End]			DateTime, 
	[PST_LAN]			DateTime, 
	[Civil_T]			DateTime, 
	[TimeZone]			Text (255), 
	[Wave_Dir]			Integer, 
	[Wave_Ht]			Integer, 
	[Wave_Prd]			Integer, 
	[Wind_Dir]			Integer, 
	[Wind_Spd]			Integer, 
	[Barometer]			Single, 
	[Dry_T]			Single, 
	[Wet_T]			Single, 
	[Wea]			Integer, 
	[Cloud_Typ]			Integer, 
	[Cloud_Amt]			Integer, 
	[Visibility]			Integer, 
	[Secchi]			Integer, 
	[ForelU]			Integer
);

CREATE TABLE [MLD_Sigma]
 (
	[ID]			Long Integer, 
	[Cast_ID]			Text (255), 
	[MLD_Sigma]			Double, 
	[CastNoSamples]			Long Integer, 
	[CastBottomSample]			Long Integer
);

CREATE TABLE [MLD_Sigma_1701-1806]
 (
	[ID]			Long Integer, 
	[Cast_ID]			Text (255), 
	[MLD_Sigma]			Double, 
	[CastNoSamples]			Long Integer, 
	[CastBottomSample]			Long Integer
);

CREATE TABLE [MLD_Sigma_orig]
 (
	[ID]			Long Integer, 
	[Cast_ID]			Text (255), 
	[MLD_Sigma]			Double, 
	[CastNoSamples]			Long Integer, 
	[CastBottomSample]			Long Integer
);

CREATE TABLE [NutClineDepth]
 (
	[Cast_No]			Long Integer, 
	[Cast_ID]			Text (255), 
	[NCDepth]			Double, 
	[NoDepths]			Double
);

CREATE TABLE [NutClineDepth_1701-1806]
 (
	[Cast_No]			Long Integer, 
	[Cast_ID]			Text (255), 
	[NCDepth]			Double, 
	[NoDepths]			Double
);

CREATE TABLE [NutClineDepth_84-201507]
 (
	[Cast_No]			Long Integer, 
	[Cast_ID]			Text (255), 
	[NCDepth]			Double, 
	[NoDepths]			Double
);

CREATE TABLE [NutClineDepth_orig]
 (
	[Cast_No]			Long Integer, 
	[Cast_ID]			Text (255), 
	[NCDepth]			Double, 
	[NoDepths]			Long Integer
);

CREATE TABLE [Nuts]
 (
	[Btl_Cnt]			Long Integer NOT NULL, 
	[PO4uM]			Single, 
	[PO4q]			Integer, 
	[SiO3uM]			Single, 
	[SiO3qu]			Integer, 
	[NO2uM]			Single, 
	[NO2q]			Integer, 
	[NO3uM]			Single, 
	[NO3q]			Integer, 
	[NH3uM]			Single, 
	[NH3q]			Integer
);

CREATE TABLE [Paste Errors]
 (
	[Cst_Cnt]			Long Integer
);

CREATE TABLE [Prodo_Cast]
 (
	[Cst_Cnt]			Long Integer NOT NULL, 
	[Inc_Str]			DateTime, 
	[Inc_End]			DateTime, 
	[PST_LAN]			DateTime, 
	[Civil_T]			DateTime, 
	[TimeZone]			Text (255), 
	[IntC14]			Single
);

CREATE TABLE [ShipCode]
 (
	[Cast_ID]			Text (255), 
	[Ship_Code]			Text (255)
);

CREATE TABLE [ShipCode_Btl]
 (
	[Depth_ID]			Text (255), 
	[Ship_Code]			Text (255)
);

CREATE TABLE [St_Stations]
 (
	[St_Line]			Single, 
	[St_Station]			Double, 
	[Sta_ID]			Text (255), 
	[DLat_Dec]			Single, 
	[DLon_Dec]			Single, 
	[Distance]			Double, 
	[Del_Dist]			Double, 
	[Del_Area]			Double, 
	[Code-SCB]			Text (50), 
	[Code-Nearshore]			Text (50), 
	[Code_Region]			Text (255)
);

CREATE TABLE [Station_ID]
 (
	[ID]			Long Integer, 
	[Sta_ID]			Text (255), 
	[DBSta_ID]			Text (255), 
	[St_Line]			Single, 
	[St_Sta]			Single, 
	[Sta_Code]			Text (255), 
	[Sta_CodeSBB]			Text (50), 
	[Sta_CodeLTER]			Text (50), 
	[DLat_Dec]			Single, 
	[DLat_Deg]			Integer, 
	[DLat_min]			Single, 
	[DLat_Hem]			Text (255), 
	[DLon_Dec]			Single, 
	[DLon_Deg]			Integer, 
	[DLon_Min]			Single, 
	[DLon_Hem]			Text (255), 
	[Distance]			Single
);

CREATE TABLE [StDepths]
 (
	[StDepth]			Long Integer
);

CREATE TABLE [Weather]
 (
	[Cst_Cnt]			Long Integer NOT NULL, 
	[Wave_Dir]			Integer, 
	[Wave_Ht]			Integer, 
	[Wave_Prd]			Integer, 
	[Wind_Dir]			Integer, 
	[Wind_Spd]			Integer, 
	[Barometer]			Single, 
	[Dry_T]			Single, 
	[Wet_T]			Single, 
	[Wea]			Integer, 
	[Cloud_Typ]			Integer, 
	[Cloud_Amt]			Integer, 
	[Visibility]			Integer, 
	[Secchi]			Integer, 
	[ForelU]			Integer
);

CREATE TABLE [Zooplankton]
 (
	[ID]			Long Integer, 
	[Cruise]			Long Integer, 
	[CruiseAlias]			Long Integer, 
	[Sta_ID]			Text (255), 
	[Cruz_Sta]			Text (255), 
	[Ship_Code]			Text (255), 
	[Order_Occ]			Long Integer, 
	[Cruz_Code]			Text (255), 
	[St_Line]			Double, 
	[St_Station]			Double, 
	[Lat_Deg]			Long Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Deg]			Long Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Tow_Type]			Text (255), 
	[Net_Loc]			Text (255), 
	[End_Time]			DateTime, 
	[Tow_Date]			DateTime, 
	[Tow_Time]			DateTime, 
	[Vol_StrM3]			Double, 
	[Tow_DpthM]			Long Integer, 
	[Ttl_PVolC3]			Long Integer, 
	[Sml_PVolC3]			Long Integer, 
	[HaulFact]			Double, 
	[Ttl_Eggs_Raw]			Text (255), 
	[Ttl_Larvae_Raw]			Text (255), 
	[Ttl_Eggs_Stnd]			Text (255), 
	[Ttl_Larvae_Stnd]			Text (255), 
	[Sardine_Eggs_Raw]			Text (255), 
	[Sardine_Eggs_Stnd]			Text (255), 
	[Anchovy_Eggs_Raw]			Text (255), 
	[Anchovy_Eggs_Stnd]			Text (255), 
	[Sardine_Larvae_Raw]			Text (255), 
	[Sardine_Larvae_Stnd]			Text (255), 
	[Anchovy_Larvae_Raw]			Text (255), 
	[Anchovy_Larvae_Stnd]			Text (255)
);

CREATE TABLE [0-Sta_Code]
 (
	[ID]			Long Integer, 
	[Sta_Code]			Text (50), 
	[Data Type Description]			Text (50), 
	[Data Type]			Text (50), 
	[Description]			Text (255)
);

CREATE TABLE [1507DIC_DB]
 (
	[ID]			Long Integer, 
	[Cruise]			Long Integer, 
	[Btl_Cnt]			Text (255), 
	[Bottle_ID]			Long Integer, 
	[Bottle_ID2]			Text (255), 
	[StaPr]			Double, 
	[Depthm]			Long Integer, 
	[Depth_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[pH1]			Double, 
	[pH2]			Double, 
	[DIC1]			Double, 
	[DIC2]			Double, 
	[TA1]			Double, 
	[TA2]			Double, 
	[Salinity1]			Double, 
	[Salinity2]			Double, 
	[D_Nisk1]			Long Integer, 
	[D_Nisk2]			Text (255), 
	[StaTemp]			Double, 
	[StaSalt]			Double, 
	[StaNisk]			Long Integer, 
	[D_Depth1]			Long Integer, 
	[D_Depth2]			Text (255), 
	[Ord_Occ]			Long Integer
);

CREATE TABLE [2105_Final_to_2304_Prelim_BTL_FIXADD2DB-btl_ImportErrors]
 (
	[Error]			Text (255), 
	[Field]			Text (255), 
	[Row]			Long Integer
);

CREATE TABLE [Bottle_Sigm]
 (
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[STheta]			Single, 
	[Depth]			Integer, 
	[Temp]			Single, 
	[Sal]			Single, 
	[O2]			Single, 
	[O2Sat]			Single, 
	[NO3]			Single, 
	[NO2]			Single, 
	[PO4]			Single, 
	[SiO4]			Single
);

CREATE TABLE [Cast_rcl]
 (
	[Cst_Cnt]			Long Integer, 
	[Cruise_ID]			Text (255), 
	[Cruise]			Long Integer, 
	[CruiseAlias]			Long Integer, 
	[Cruz_Sta]			Text (255), 
	[DbSta_ID]			Text (255), 
	[Cast_ID]			Text (255), 
	[Sta_ID]			Text (255), 
	[Quarter]			Long Integer, 
	[Sta_Code]			Text (255), 
	[Distance]			Text (255), 
	[Date]			DateTime, 
	[Year]			Long Integer, 
	[Month]			Long Integer, 
	[Julian_Date]			Long Integer, 
	[Julian_Day]			Long Integer, 
	[Time]			Text (255), 
	[Lat_Dec]			Double, 
	[Lat_Deg]			Long Integer, 
	[Lat_Min]			Double, 
	[Lat_Hem]			Text (255), 
	[Lon_Dec]			Double, 
	[Lon_Deg]			Long Integer, 
	[Lon_Min]			Double, 
	[Lon_Hem]			Text (255), 
	[Rpt_Line]			Text (255), 
	[St_Line]			Double, 
	[Ac_Line]			Double, 
	[Rpt_Sta]			Text (255), 
	[St_Station]			Double, 
	[Ac_Sta]			Double, 
	[Bottom_D]			Text (255), 
	[Secchi]			Text (255), 
	[ForelU]			Text (255), 
	[Ship_Name]			Text (255), 
	[Ship_Code]			Text (255), 
	[Data_Type]			Text (255), 
	[Order_Occ]			Text (255), 
	[Event_Num]			Long Integer, 
	[Cruz_Leg]			Text (255), 
	[Orig_Sta_ID]			Text (255), 
	[Data_Or]			Text (255), 
	[Cruz_Num]			Text (255), 
	[IntChl]			Text (255), 
	[IntC14]			Text (255)
);

CREATE TABLE [Cruises]
 (
	[ID]			Long Integer, 
	[Cruise]			Long Integer, 
	[Code-ST]			Text (50), 
	[Code-SC]			Text (50), 
	[Code-L90]			Text (50), 
	[Ship1]			Text (255), 
	[BegDate1]			DateTime, 
	[EndDate1]			DateTime, 
	[StasOcc1]			Integer, 
	[Ship2]			Text (255), 
	[BegDate2]			DateTime, 
	[EndDate2]			DateTime, 
	[StasOcc2]			Integer, 
	[Ship3]			Text (255), 
	[BegDate3]			DateTime, 
	[EndDate3]			DateTime, 
	[StasOcc3]			Integer, 
	[Ship4]			Text (255), 
	[BegDate4]			DateTime, 
	[EndDate4]			DateTime, 
	[StasOcc4]			Integer, 
	[Ship5]			Text (255), 
	[BegDate5]			DateTime, 
	[EndDate5]			DateTime, 
	[StasOcc5]			Integer, 
	[Ship6]			Text (255), 
	[BegDate6]			DateTime, 
	[EndDate6]			DateTime, 
	[StasOcc6]			Integer, 
	[Captain1]			Text (255), 
	[Captain2]			Text (255), 
	[Captain3]			Text (255), 
	[Captain4]			Text (255), 
	[Captain5]			Text (255), 
	[Leg1_Date]			Text (255), 
	[Leg1_Locations]			Text (255), 
	[Leg2_Date]			Text (255), 
	[Leg2_Locations]			Text (255), 
	[Leg3_Date]			Text (255), 
	[Leg3_Locations]			Text (255), 
	[Leg4_Date]			Text (255), 
	[Leg4_Locations]			Text (255), 
	[Leg5_Date]			Text (255), 
	[Leg5_Locations]			Text (255)
);

CREATE TABLE [DIC_ABS_salCompare]
 (
	[SalComp]			Double, 
	[Depth_ID]			Text (255), 
	[Btl_Cnt]			Long Integer, 
	[Salnty]			Single, 
	[Salinity1]			Double, 
	[Bottle_ID1]			Long Integer, 
	[Cruise]			Long Integer, 
	[Comments]			Text (255)
);

CREATE TABLE [Mati_Hydro_2111_finalthru2001]
 (
	[Cruise]			Long Integer, 
	[Sta_ID]			Text (255), 
	[Depthm]			Integer, 
	[T_degC]			Single, 
	[Salnty]			Single, 
	[O2ml_L]			Single, 
	[ChlorA]			Single, 
	[Phaeop]			Single, 
	[PO4uM]			Single, 
	[SiO3uM]			Single, 
	[NO2uM]			Single, 
	[NO3uM]			Single, 
	[NH3uM]			Single, 
	[Cst_Cnt]			Long Integer, 
	[Btl_Cnt]			Long Integer NOT NULL, 
	[STheta]			Single, 
	[O2Sat]			Single, 
	[Oxy_µmol/Kg]			Single
);

CREATE TABLE [Prodo_Bottle]
 (
	[Cst_Cnt]			Long Integer, 
	[Btl_Cnt]			Long Integer NOT NULL, 
	[C14As1]			Single, 
	[C14A1p]			Integer, 
	[C14A1q]			Integer, 
	[C14As2]			Single, 
	[C14A2p]			Integer, 
	[C14A2q]			Integer, 
	[DarkAs]			Single, 
	[DarkAp]			Integer, 
	[DarkAq]			Integer, 
	[MeanAs]			Single, 
	[MeanAp]			Integer, 
	[MeanAq]			Integer, 
	[IncTim]			DateTime, 
	[LightP]			Single
);

CREATE TABLE [Rpt_Data]
 (
	[Btl_Cnt]			Long Integer NOT NULL, 
	[R_Depth]			Single, 
	[R_TEMP]			Single, 
	[R_POTEMP]			Single, 
	[R_SALINITY]			Single, 
	[R_SIGMA]			Single, 
	[R_SVA]			Single, 
	[R_DYNHT]			Single, 
	[R_O2]			Single, 
	[R_O2Sat]			Single, 
	[R_SIO3]			Single, 
	[R_PO4]			Single, 
	[R_NO3]			Single, 
	[R_NO2]			Single, 
	[R_NH4]			Single, 
	[R_CHLA]			Single, 
	[R_PHAEO]			Single, 
	[R_PRES]			Integer, 
	[R_SAMP]			Integer, 
	[R_Oxy_µmol/Kg]			Single
);


