---
config:
  layout: elk
---
erDiagram
    cruise {
        varchar cruise_uuid
        date date_ym
        varchar ship_key FK
        varchar _source_file
        int _source_row
        timestamp _ingested_at
        varchar _source_uuid
        varchar cruise_key PK
    }
    ichthyo {
        varchar ichthyo_uuid PK
        varchar net_uuid FK
        double species_id FK
        varchar life_stage
        varchar measurement_type
        double measurement_value
        double tally
        varchar _source_file
        int _source_row
        timestamp _ingested_at
        varchar _source_uuid
    }
    invert {
        varchar net_uuid
        double species_id
        double tally
        varchar _source_file
        int _source_row
        timestamp _ingested_at
        varchar _source_uuid
    }
    lookup {
        int lookup_id PK
        varchar lookup_type
        int lookup_num
        varchar lookup_chr
        varchar description
        varchar _source_file
        int _source_row
        varchar _ingested_at
        varchar _source_uuid
    }
    net {
        varchar net_uuid PK
        varchar tow_uuid FK
        varchar side
        double std_haul_factor
        double vol_sampled_m3
        double prop_sorted
        double smallplankton
        double totalplankton
        varchar _source_file
        int _source_row
        timestamp _ingested_at
        varchar _source_uuid
    }
    ship {
        varchar ship_key PK
        varchar ship_name
        varchar ship_nodc
        varchar _source_file
        int _source_row
        timestamp _ingested_at
        varchar _source_uuid
    }
    site {
        varchar site_uuid PK
        varchar cruise_uuid
        double orderocc
        double longitude
        double latitude
        double line
        double station
        varchar _source_file
        int _source_row
        timestamp _ingested_at
        varchar _source_uuid
        varchar cruise_key FK
    }
    species {
        double species_id PK
        varchar scientific_name
        double itis_id
        double worms_id
        varchar common_name
        varchar _source_file
        int _source_row
        timestamp _ingested_at
        varchar _source_uuid
        int gbif_id
    }
    taxa_rank {
        varchar taxonRank PK
        int rank_order
    }
    taxon {
        varchar authority
        int taxonID PK
        int acceptedNameUsageID
        int parentNameUsageID
        varchar scientificName
        varchar taxonRank FK
        varchar taxonomicStatus
        varchar scientificNameAuthorship
    }
    tow {
        varchar tow_uuid PK
        varchar site_uuid FK
        varchar tow_type_key
        double tow_number
        timestamp time_start
        varchar _source_file
        int _source_row
        timestamp _ingested_at
        varchar _source_uuid
    }
    net ||--o{ ichthyo : "net_uuid"
    species ||--o{ ichthyo : "species_id"
    tow ||--o{ net : "tow_uuid"
    site ||--o{ tow : "site_uuid"
    cruise ||--o{ site : "cruise_key"
    ship ||--o{ cruise : "ship_key"
    taxa_rank ||--o{ taxon : "taxonRank"
