---
config:
  layout: elk
---
erDiagram
    mesopelagic_fish_tow {
        int tow_id PK
        int tow_number
        varchar cruise_key
        varchar ship_key
        double latitude
        double longitude
        timestamp datetime_start_utc
        bool hour_source_conflict
        int tow_year
        int tow_month
        double tow_hour
        double tow_minute
        varchar station_raw
        double depth_m
        double volume_sampled
        double density_total_qc
        double abundance_total_qc
        geometry geom
        varchar grid_key
        varchar site_key
    }
    mesopelagic_fish_taxon {
        int taxon_id PK
        varchar scientific_name
        int worms_id
        int itis_id
    }
    mesopelagic_fish_measurement {
        varchar measurement_type FK
        int mesopelagic_fish_measurement_id PK
        int tow_id FK
        varchar scientific_name FK
        double measurement_value
    }
    measurement_type {
        varchar measurement_type PK
        varchar description
        varchar units
        bool is_canonical
        varchar _source_column
        varchar _source_table
        varchar _source_datasets
        varchar _qual_column
        varchar _prec_column
        varchar grain
    }
    dataset {
        varchar provider
        varchar dataset
        varchar dataset_name
        varchar description
        varchar citation_main
        varchar citation_others
        varchar link_calcofi_org
        varchar link_data_source
        varchar link_others
        varchar tables
        varchar coverage_temporal
        varchar coverage_spatial
        varchar license
        varchar pi_names
    }
    mesopelagic_fish_tow ||--o{ mesopelagic_fish_measurement : "tow_id"
    mesopelagic_fish_taxon ||--o{ mesopelagic_fish_measurement : "scientific_name"
    measurement_type ||--o{ mesopelagic_fish_measurement : "measurement_type"
    classDef lightblue stroke:#ADD8E6,stroke-width:3px
    class mesopelagic_fish_tow,mesopelagic_fish_measurement lightblue
    classDef lightgreen stroke:#90EE90,stroke-width:3px
    class mesopelagic_fish_taxon lightgreen
    classDef lightyellow stroke:#FFFFE0,stroke-width:3px
    class measurement_type lightyellow
    classDef white stroke:#FFFFFF,stroke-width:3px
    class dataset white
