---
config:
  layout: elk
---
erDiagram
    bird_mammal_transect {
        varchar gis_key PK
        varchar cruise_label
        int transect_number
        int bin_number
        double latitude
        double longitude
        double length_m
        double width_m
        double area_m2
        int core_flag
        varchar season
        timestamp datetime_start_utc
        date date
        geometry geom
        varchar grid_key
        varchar cruise_key
    }
    bird_mammal_observation {
        varchar gis_key FK
        varchar species_code FK
        varchar behavior_code FK
        int count
        varchar observation_id PK
    }
    bird_mammal_species {
        varchar species_code PK
        varchar common_name
        varchar scientific_name
        varchar type
        bool is_bird
        bool is_mammal
        bool is_fish
        bool is_turtle
        int itis_id
        bool is_unidentified
        bool include_flag
        varchar scientific_name_datazoo
    }
    bird_mammal_behavior {
        varchar behavior_code PK
        varchar behavior
        varchar description
    }
    dataset {
        varchar provider
        varchar dataset
        varchar dataset_name
        varchar dataset_name_short
        varchar category
        varchar color
        varchar description
        varchar citation_main
        varchar citation_others
        varchar link_calcofi_org
        varchar link_data_source
        varchar link_others
        varchar tables
        varchar coverage_temporal
        varchar coverage_spatial
        varchar license
        varchar pi_names
        varchar doi
        varchar license_url
        varchar acknowledgement
        varchar contact
    }
    bird_mammal_transect ||--o{ bird_mammal_observation : "gis_key"
    bird_mammal_species ||--o{ bird_mammal_observation : "species_code"
    bird_mammal_behavior ||--o{ bird_mammal_observation : "behavior_code"
    classDef lightblue stroke:#ADD8E6,stroke-width:3px
    class bird_mammal_transect,bird_mammal_observation lightblue
    classDef lightyellow stroke:#FFFFE0,stroke-width:3px
    class bird_mammal_species,bird_mammal_behavior lightyellow
    classDef white stroke:#FFFFFF,stroke-width:3px
    class dataset white
