---
config:
  layout: elk
---
erDiagram
    zooplankton_tow {
        varchar expedition
        varchar expedition_code
        varchar expedition_type
        varchar ship_name
        int order_occ
        double line
        double station
        double latitude
        double longitude
        date date
        timestamp datetime_start_utc
        timestamp datetime_end_utc
        double depth_min_m
        double depth_max_m
        double max_wire_out_m
        varchar net_type
        double mesh_size_mm
        varchar tow_type
        varchar fixative
        varchar preservative
        varchar site_key
        int tow_id PK
        varchar ship_key
        varchar cruise_key
        geometry geom
        varchar grid_key
    }
    dataset {
        varchar provider
        varchar dataset
        varchar dataset_name
        varchar description
        varchar citation_main
        varchar citation_others
        varchar link_calcofi_org
        varchar link_data_source
        varchar link_others
        varchar tables
        varchar coverage_temporal
        varchar coverage_spatial
        varchar license
        varchar pi_names
    }
    classDef lightblue stroke:#ADD8E6,stroke-width:3px
    class zooplankton_tow lightblue
    classDef white stroke:#FFFFFF,stroke-width:3px
    class dataset white
