#!/usr/bin/env Rscript
# Generate the Caddy `map` entries that send a legacy release-parquet path
# (releases/{v}/parquet/{table}.parquet or a partition file) to its canonical
# content-addressed object, for every canonical-layout release in versions.json.
# Consulted by storage.calcofi.io on 404 only, so entries for versions that still
# have compat copies are harmless. Output: server/caddy/releases_redirects.caddy
#
#   Rscript scripts/build_release_redirects.R [--prefix ducklake/releases] [--out path]
suppressMessages({library(jsonlite); library(glue)})
`%||%` <- function(a, b) if (is.null(a)) b else a
args   <- commandArgs(trailingOnly = TRUE)
opt    <- function(flag, default) { i <- match(flag, args); if (is.na(i)) default else args[i + 1] }
prefix <- opt("--prefix", "ducklake/releases")
out    <- opt("--out", here::here("../server/caddy/releases_redirects.caddy"))
bucket <- "calcofi-db"
https  <- function(p) glue("https://storage.googleapis.com/{bucket}/{p}")
versions <- tryCatch(fromJSON(https(glue("{prefix}/versions.json")), simplifyVector = FALSE)$versions,
                     error = function(e) list())
lines <- c("# generated by CalCOFI/workflows scripts/build_release_redirects.R — do not edit",
           "# <legacy path>  <canonical https URL>")
n <- 0
for (v in versions) {
  cat_ <- tryCatch(fromJSON(https(glue("{prefix}/{v$version}/catalog.json")), simplifyVector = FALSE),
                   error = function(e) NULL)
  if (is.null(cat_) || !identical(cat_$layout, "canonical")) next
  for (t in cat_$tables) {
    if (is.null(t$compat_path)) next
    for (o in t$objects) {
      legacy <- o$compat_path %||% (if (is.null(o$partition_by)) t$compat_path else
        glue("{t$compat_path}{o$partition_by}={o$partition_value}/data_0.parquet"))
      lines <- c(lines, glue("\t\t\t/{bucket}/{legacy}\t{https(o$path)}"))
      n <- n + 1
    }
  }
}
writeLines(lines, out)
cat(glue("{n} redirect(s) for {length(versions)} version(s) under {prefix} -> {out}\n"))
