# erddap_deploy.R — push a generated ERDDAP config to the live server.
#
# publish_to-erddap.qmd GENERATES config and a view-build script; this performs
# the five deploy steps its "Deploy" section documents. Gated by the caller
# (CALCOFI_ERDDAP_DEPLOY=true) because it mutates a public production service.
#
# Split out of the notebook so each step is a named function that fails loudly on
# its own, rather than a block of shell that half-succeeds. Every trap encoded
# here was hit for real on 2026-08-04 and every one of them fails QUIETLY:
#
#   * `sudo git pull` fails — root has no GitHub credentials. Fetch as the ssh
#     user (who does), then `sudo git merge --ff-only`, which needs no network.
#     The bare `git pull` prints "Updating <a>..<b>" and then dies on the write,
#     so its output looks like success if you only read the first line.
#   * The erddap checkout is owned by uids that are not the ssh user (repo 1003,
#     content/datasets.xml 1000, both group 50). A root merge silently re-owns
#     them and the NEXT unprivileged pull then fails. Ownership is captured
#     before and restored after.
#   * The flag directories are drwxrws--- under a group the ssh user is not in,
#     so an unprivileged `ls` reports zero flags whether or not they exist, and
#     ERDDAP deletes each flag as it consumes it. Neither "0 flags" nor "flags
#     present" means anything: verification MUST come from the live service.
#   * datasets.xml contains BOTH an `add dataset definitions below` marker and a
#     `BEGIN/END generated` pair. Splicing at the former APPENDS, silently
#     duplicating every dataset; only replacing between BEGIN/END is idempotent.

`%||%` <- function(x, y) if (is.null(x) || length(x) == 0) y else x

ERDDAP_BEGIN <- "<!-- BEGIN generated by publish_to-erddap.qmd -->"
ERDDAP_END   <- "<!-- END generated by publish_to-erddap.qmd -->"

#' Run a command over ssh, stopping on a non-zero exit.
#' @param host ssh host alias.
#' @param cmd  remote command.
#' @param what label used in the error message.
#' @return character vector of combined stdout/stderr.
ssh_run <- function(host, cmd, what = "remote command") {
  out <- system2("ssh", c(host, shQuote(cmd)), stdout = TRUE, stderr = TRUE)
  rc  <- attr(out, "status") %||% 0L
  # ssh -R port-forward warnings are emitted by this host's config and are noise
  out <- out[!grepl("remote port forwarding failed|bind \\[|channel_setup_fwd|Could not request local forwarding", out)]
  if (rc != 0)
    stop(sprintf("%s failed (exit %s):\n%s", what, rc,
                 paste(utils::tail(out, 20), collapse = "\n")))
  out
}

#' Step 1 — pull the release parquet to the identity-mounted server path.
#'
#' Pulled server-side from GCS rather than pushed: rsync is absent on the server
#' and the bytes are already in the bucket, so a laptop upload is pure waste.
erddap_sync_parquet <- function(host, erddap_root, release, gcs_bucket = "calcofi-db") {
  cmd <- sprintf(paste(
    "mkdir -p %s/datasets/release/%s",
    "&& gsutil -m cp -r gs://%s/ducklake/releases/%s/parquet %s/datasets/release/%s/",
    "&& gsutil -m cp -r gs://%s/ingest/calcofi_mets %s/datasets/ingest/"),
    erddap_root, release, gcs_bucket, release, erddap_root, release,
    gcs_bucket, erddap_root)
  ssh_run(host, cmd, "parquet sync")
  n <- ssh_run(host, sprintf(
    "find %s/datasets/release/%s -name '*.parquet' | wc -l", erddap_root, release))
  n <- as.integer(utils::tail(n, 1))
  if (is.na(n) || n == 0)
    stop("parquet sync landed no files under ", erddap_root, "/datasets/release/", release)
  n
}

#' Step 2 — build the DuckDB view database ON the server.
#'
#' Cannot be built locally: DuckDB validates a view's parquet paths at CREATE
#' time, so the views must be created where the data sits at the path they name.
#' A view reporting zero rows means step 1 was incomplete — the cheapest place to
#' catch it, so it is an error rather than a warning.
erddap_build_db <- function(host, erddap_root, script_path) {
  if (!file.exists(script_path)) stop("missing generated script: ", script_path)
  rc <- system2("scp", c(script_path, sprintf("%s:%s/", host, erddap_root)),
                stdout = TRUE, stderr = TRUE)
  if ((attr(rc, "status") %||% 0L) != 0)
    stop("scp of build_erddap_db.R failed: ", paste(rc, collapse = " "))
  out <- ssh_run(host, sprintf(
    "docker exec -i rstudio bash -lc 'cd %s && Rscript build_erddap_db.R'",
    erddap_root), "view database build")
  zero <- grep("\\s0 rows\\s*$", out, value = TRUE)
  if (length(zero))
    stop("views built with ZERO rows (parquet sync incomplete):\n",
         paste(zero, collapse = "\n"))
  out
}

#' Splice the generated blocks into the erddap repo's datasets.xml.
#'
#' Replaces everything between BEGIN/END, so hand-maintained datasets OUTSIDE
#' that block survive and re-running is idempotent. Returns the id sets so the
#' caller can flag added/changed datasets and hard-flag retired ones.
erddap_splice_config <- function(repo_dir, generated_xml) {
  cfg_path <- file.path(repo_dir, "content", "datasets.xml")
  stopifnot("erddap config not found" = file.exists(cfg_path),
            "generated xml not found" = file.exists(generated_xml))
  txt <- paste(readLines(cfg_path, warn = FALSE), collapse = "\n")
  gen <- trimws(paste(readLines(generated_xml, warn = FALSE), collapse = "\n"))
  b <- regexpr(ERDDAP_BEGIN, txt, fixed = TRUE)
  e <- regexpr(ERDDAP_END,   txt, fixed = TRUE)
  if (b < 0 || e < 0 || e < b)
    stop("BEGIN/END generated markers not found (or out of order) in ", cfg_path,
         " — refusing to splice, since appending at the 'add dataset definitions",
         " below' marker would duplicate every dataset instead of replacing them")
  ids <- function(s) unique(regmatches(s, gregexpr('(?<=datasetID=")[^"]+', s, perl = TRUE))[[1]])
  old_ids <- ids(substr(txt, b, e - 1))
  new_ids <- ids(gen)
  out <- paste0(substr(txt, 1, b - 1), ERDDAP_BEGIN, "\n", gen, "\n",
                substr(txt, e, nchar(txt)))
  writeLines(out, cfg_path)
  # a malformed datasets.xml takes every dataset down, not just the new ones
  ok <- tryCatch({ xml2::read_xml(cfg_path); TRUE }, error = function(e) conditionMessage(e))
  if (!isTRUE(ok)) stop("spliced datasets.xml is not well-formed XML: ", ok)
  list(added   = setdiff(new_ids, old_ids),
       retired = setdiff(old_ids, new_ids),
       all     = new_ids,
       kept_outside = setdiff(ids(paste0(substr(txt, 1, b - 1),
                                         substr(txt, e, nchar(txt)))), character(0)))
}

#' Commit + push the erddap repo, then fast-forward the server's checkout.
#'
#' The host merge is deliberately two commands: the fetch runs as the ssh user
#' (who holds the GitHub credentials) and the merge runs as root (who holds the
#' write permission but NOT the credentials). Ownership is captured before and
#' restored after, because a root merge otherwise re-owns the tree and breaks the
#' next unprivileged fetch.
erddap_push_config <- function(host, repo_dir, remote_repo, release, msg = NULL) {
  git <- function(...) {
    # shQuote each argument: system2() does NOT quote — it pastes its args into a
    # shell command — so any argument containing a space is split into several.
    # The commit message always contains spaces, so
    #   git commit -q -m datasets: repoint at release v2026.08.07
    # reached git as `-m datasets:` plus four bogus pathspecs, and the deploy died
    # with "pathspec 'repoint' did not match any file(s) known to git".
    # (Same trap as prime_zips_from_gcs() in ingest_calcofi_ctd-cast.qmd, where an
    # unquoted "~/My Drive/..." path split on its space.)
    args <- c("-C", repo_dir, ...)
    out <- system2("git", shQuote(args), stdout = TRUE, stderr = TRUE)
    if ((attr(out, "status") %||% 0L) != 0)
      stop("git ", paste(..., collapse = " "), " failed: ", paste(out, collapse = " "))
    out
  }
  if (!length(git("status", "--porcelain", "content/datasets.xml"))) {
    message("erddap config unchanged — nothing to push")
  } else {
    git("add", "content/datasets.xml")
    git("commit", "-q", "-m",
        msg %||% sprintf("datasets: repoint at release %s", release))
    git("push", "-q")
  }
  own <- ssh_run(host, sprintf(
    "stat -c '%%u:%%g' %s %s/content/datasets.xml", remote_repo, remote_repo))
  own <- own[grepl("^[0-9]+:[0-9]+$", own)]
  if (length(own) < 2) stop("could not read remote ownership: ", paste(own, collapse = " "))
  ssh_run(host, sprintf("git -C %s fetch --quiet origin", remote_repo), "host fetch")
  ssh_run(host, sprintf("sudo git -C %s merge --ff-only origin/main", remote_repo),
          "host fast-forward")
  ssh_run(host, sprintf("sudo chown -R %s %s && sudo chown %s %s/content/datasets.xml",
                        own[1], remote_repo, own[2], remote_repo), "ownership restore")
  invisible(own)
}

#' Step 4 — flag datasets for reload; hard-flag the retired ones so ERDDAP
#' forgets them. Created as root then chowned, so ERDDAP can delete them.
erddap_flag <- function(host, flag_dir, reload_ids, retire_ids = character()) {
  hard_dir <- file.path(dirname(flag_dir), "hardFlag")
  sh <- c(
    if (length(reload_ids))
      sprintf("for d in %s; do sudo touch %s/$d; done",
              paste(reload_ids, collapse = " "), flag_dir),
    if (length(retire_ids))
      sprintf("for d in %s; do sudo touch %s/$d; done",
              paste(retire_ids, collapse = " "), hard_dir),
    sprintf("sudo chown 1000 %s/* %s/* 2>/dev/null || true", flag_dir, hard_dir))
  ssh_run(host, paste(sh, collapse = "; "), "flagging")
  invisible(TRUE)
}

#' Step 5 — verify against the LIVE service, which is the only trustworthy
#' signal: the flag directory is unreadable unprivileged and self-clearing.
erddap_verify <- function(base_url, expect_present = character(),
                          expect_absent = character()) {
  code <- function(id) {
    u <- sprintf("%s/erddap/info/%s/index.json", sub("/$", "", base_url), id)
    as.integer(system2("curl", c("-s", "-o", "/dev/null", "-w", "%{http_code}",
                                 "--max-time", "60", shQuote(u)), stdout = TRUE))
  }
  res <- rbind(
    if (length(expect_present))
      data.frame(datasetID = expect_present, expect = 200L,
                 got = vapply(expect_present, code, integer(1))),
    if (length(expect_absent))
      data.frame(datasetID = expect_absent, expect = 404L,
                 got = vapply(expect_absent, code, integer(1))))
  if (is.null(res)) return(invisible(NULL))
  res$ok <- res$expect == res$got
  if (any(!res$ok))
    warning("ERDDAP verification failed for: ",
            paste(res$datasetID[!res$ok], collapse = ", "))
  res
}
