-- query: Anomalies Sigma 0 IM
-- type:  SELECT
-- source: CalCOFI_4903-2304_Master_Final_through_2105_October162023.accdb (ACE12), extracted via Jackcess

SELECT Cast.Cruise, Bottle_Sigm.Cast_ID, Cast.Sta_ID, Cast.Date, Cast.Julian_Day, Cast.Year, Year([Date])+Month([Date])/12 AS YearValue, Cast.Time, HarmCoeffSigma.StSigma AS Sigma, Bottle_Sigm.Depth AS Depth, Bottle_Sigm.Temp AS Temp, Bottle_Sigm.Sal AS Sal, Bottle_Sigm.O2 AS O2, Bottle_Sigm.O2Sat AS O2Sat, Bottle_Sigm.NO3 AS NO3, Bottle_Sigm.PO4 AS PO4, Bottle_Sigm.SiO4 AS SiO4, Avg(HarmCoeffSigma.DepthStDev) AS DepthStDev, Avg(HarmCoeffSigma.TempStDev) AS TempStDev, Avg(HarmCoeffSigma.SalStDev) AS SalStDev, Avg(HarmCoeffSigma.O2StDev) AS O2StDev, Avg(HarmCoeffSigma.NO3StDev) AS NO3StDev, Avg(HarmCoeffSigma.PO4StDev) AS PO4StDev, Avg(HarmCoeffSigma.SiO3StDev) AS SiO3StDev, Avg(Bottle_Sigm!Depth-(HarmCoeffSigma!DepthMean+HarmCoeffSigma!DepthAmpl*Sin(HarmCoeffSigma!DepthFreq*([Julian_Day]-HarmCoeffSigma!DepthPhase)))) AS DepthAnom, Avg(Bottle_Sigm!Temp-(HarmCoeffSigma!TempMean+HarmCoeffSigma!TempAmpl*Sin(HarmCoeffSigma!TempFreq*([Julian_Day]-HarmCoeffSigma!TempPhase)))) AS TempAnom, Avg(Bottle_Sigm!Sal-(HarmCoeffSigma!SalMean+HarmCoeffSigma!SalAmpl*Sin(HarmCoeffSigma!SalFreq*([Julian_Day]-HarmCoeffSigma!SalPhase)))) AS SalAnom, Avg(Bottle_Sigm!O2-(HarmCoeffSigma!O2Mean+HarmCoeffSigma!O2Ampl*Sin(HarmCoeffSigma!O2Freq*([Julian_Day]-HarmCoeffSigma!O2Phase)))) AS O2Anom, Avg(Bottle_Sigm!NO3-(HarmCoeffSigma!NO3Mean+HarmCoeffSigma!NO3Ampl*Sin(HarmCoeffSigma!NO3Freq*([Julian_Day]-HarmCoeffSigma!NO3Phase)))) AS NO3Anom, Avg(Bottle_Sigm!PO4-(HarmCoeffSigma!PO4Mean+HarmCoeffSigma!PO4Ampl*Sin(HarmCoeffSigma!PO4Freq*([Julian_Day]-HarmCoeffSigma!PO4Phase)))) AS PO4Anom, Avg(Bottle_Sigm!SiO4-(HarmCoeffSigma!SiO3Mean+HarmCoeffSigma!SiO3Ampl*Sin(HarmCoeffSigma!SiO3Freq*([Julian_Day]-HarmCoeffSigma!SiO3Phase)))) AS SiO3Anom, ([NO3]/[PO4]) AS [N-P_Ratio], ((([NO3]-16*[PO4]+2.9))) AS [N-Star]
FROM (Cast INNER JOIN HarmCoeffSigma ON Cast.Sta_ID = HarmCoeffSigma.Sta_ID) INNER JOIN Bottle_Sigm ON (HarmCoeffSigma.StSigma = Bottle_Sigm.STheta) AND (Cast.Cast_ID = Bottle_Sigm.Cast_ID)
WHERE (((Bottle_Sigm.STheta)=[HarmCoeffSigma]![StSigma]))
GROUP BY Cast.Cruise, Bottle_Sigm.Cast_ID, Cast.Sta_ID, Cast.Date, Cast.Julian_Day, Cast.Year, Cast.Time, HarmCoeffSigma.StSigma, Bottle_Sigm.Depth, Bottle_Sigm.Temp, Bottle_Sigm.Sal, Bottle_Sigm.O2, Bottle_Sigm.O2Sat, Bottle_Sigm.NO3, Bottle_Sigm.PO4, Bottle_Sigm.SiO4
ORDER BY Cast.Cruise, Cast.Sta_ID, HarmCoeffSigma.StSigma;
